### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume1/Media/shared/Animes/TV Shows/\xe4\xba\xba\xe9\xad\x9a\xe4\xb9\x8b\xe6\xa3\xae/[Henshin]_Ningyo_no_Mori_04.en.srt'

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4880] opened 2018-08-14 13:17 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/a98173925a01896bf484014e5e6ab775
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for 高橋留美子劇場 人魚の森 S01E04. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 16:56
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/ae1b701ad61fcf1f295c8c388dc04d6e
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for 高橋留美子劇場 人魚の森 S01E04. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:15
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/d71a0cc587ffafd37ec16e2db06672d1
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for 高橋留美子劇場 人魚の森 S01E04. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-10-27 01:40
Duplicate of #4874

**Closed by WebSpider** 2018-10-27 01:40 UTC
