### ISSUE TITLE
[APP SUBMITTED]: FINDPROPERS :: [53e6cc5] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by MarioCaires** [SickChill/SickChill#4395] opened 2018-03-15 10:38 UTC
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
Link to Log: https://gist.github.com/5e9610636178f90dfe4bd15ec99d3628
### ERROR
```
FINDPROPERS :: [53e6cc5] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MarioCaires** [comment] 2018-03-15 10:39
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53e6cc50c086757c31fc518b550d7681c61649e6
Link to Log: https://gist.github.com/3c8308bc7401153d1fb8f5539829d455
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [53e6cc5] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 22:49
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:49 UTC
