### ISSUE TITLE
INFO::SEARCHQUEUE-MANUAL-326124 :: [Jackett] :: Request failed: HTTPConnectionPool(host='192.168.1.10', port=9117): Read timed out

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5461] opened 2019-05-07 16:50 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
any search now responds with;
INFO::SEARCHQUEUE-MANUAL-326124 :: [Jackett] :: Request failed: HTTPConnectionPool(host='192.168.1.10', port=9117): Read timed out
What happened:
Nothing......  just moves on
What you expected:
It to return a search results..  (i can find the results if I manually search for the same item)
Logs:
onlt thing in the logs is whats posted (error)
PASTE LOGS HERE
```
I think that [Jackett} can take longer to return results depending on the number if sites it searches and their response times..  I'll play wit it some more and see what I can figure out..
I use Jackett with other search programs without any problems. They use the same search sites.

**Comment by WebSpider** [comment] 2019-05-27 07:34
Duplicate of #5432

**Closed by WebSpider** 2019-05-27 07:34 UTC
