### ISSUE TITLE
Missing Cover Art

### ISSUE THREAD

**Issue by mike2246** [SickChill/SickChill#5713] opened 2019-11-20 15:33 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Developer
OS: 10
Browser: Chrome
What you did: Added Show
What happened: No Cover Art on Main Screen
What you expected:
Logs:
```
PASTE LOGS HERE
```
Log File
2019-11-20 15:30:05 INFO TORNADO :: Could not start webserver on port 8082: already in use!
2019-11-20 15:30:05 INFO TORNADO :: Starting SickChill on http://0.0.0.0:8082/
2019-11-20 15:30:05 INFO MAIN :: Starting SickChill [develop] using '/home/walruse/sickchill/config.ini'
2019-11-20 15:30:05 INFO MAIN :: 359123: Unable to find IMDb show info in the database
2019-11-20 15:30:04 INFO MAIN :: 81252: Unable to find IMDb show info in the database
2019-11-20 15:28:32 INFO SHOWQUEUE-ADD :: Done cache check
2019-11-20 15:28:31 WARNING SHOWQUEUE-ADD :: There was an error trying to retrieve the image, aborting
2019-11-20 15:28:31 INFO SHOWQUEUE-ADD :: Request failed: 403 Client Error: Forbidden for url: https://artworks.thetvdb.com/banners/_cache/posters/5d998c1aa5fbe.jpg ()
2019-11-20 15:28:29 INFO SHOWQUEUE-ADD :: 342059: Updating NFOs for show with new indexer info
2019-11-20 15:28:27 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2019-11-20 15:28:27 INFO SHOWQUEUE-ADD :: 342059: Unable to find the show in the database
2019-11-20 15:28:27 INFO SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/home/walruse/sickchill/cache/indexers/theTVDB', u'language': 'en'}
2019-11-20 15:28:27 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /home/walruse/Kids TV/Big City Greens

**Comment by LeeThompson** [comment] 2019-11-22 06:20
This is due to stuff getting changed and moved around at thetvdb.   (See #5686, #5710)
Unfortunately since thetvdb staff is still working on issues (https://forums.thetvdb.com/viewtopic.php?f=122&t=60239) the best stance at this moment is to wait see what all is still broken at the end of their efforts and then work on code changes.

**Comment by cyberden** [comment] 2019-12-03 14:28
Hello.

I still have the same issue running SickChill on a synology nas using the "sickbeard custom" package.

I tried to debug the code on a windows box and it seemed to work fine.

I have this type of errors :

2019-12-03 15:24:40 INFO SHOWQUEUE-REFRESH :: Done cache check
2019-12-03 15:24:40 WARNING SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
2019-12-03 15:24:40 INFO SHOWQUEUE-REFRESH :: Request failed: HTTPSConnectionPool(host='artworks.thetvdb.com', port=443): Max retries exceeded with url: /banners/graphical/336261-g_t.jpg (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',)) ()
2019-12-03 15:24:40 WARNING SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
2019-12-03 15:24:40 INFO SHOWQUEUE-REFRESH :: Request failed: HTTPSConnectionPool(host='artworks.thetvdb.com', port=443): Max retries exceeded with url: /banners/posters/336261-2_t.jpg (Caaused by NewConnectionError(': Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',)) ()
2019-12-03 15:24:40 WARNING SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting

Anything I could do about it?

Thanks.

**Comment by ronilaukkarinen** [comment] 2019-12-08 13:52
I also get forbiddens for couple of shows (The Walking Dead and Servant) for poster only. All other shows work fine with posters, banners etc.. Pretty much the same log than the others previously on this issue. What's up?

**Comment by ronilaukkarinen** [comment] 2019-12-08 13:55
Temporary "solution":

1. Go to your sickchill folder: e. g. `cd /home/rolle/SickChill/cache/images`
2. Check out the id by clicking the poster on SickChill
3. `cp 368126.poster.jpg thumbnails/`

For some reason only thumbnail doesn't get fetched. All others seem to be in the cache dir. This ways you can fix showing the images before the fix.

**Comment by cbinder4** [comment] 2019-12-19 14:39
I tried this temp solution and indeed found the proper file xxxxxx.poster.jpg was missing from the thumbnails subdir, but when I copied it the image is still not appearing in SickChill.  I did a forced refresh on the browser and still nothing.  Is there some maintenance activity that SickChill needs to run to "see" the image?

**Comment by ronilaukkarinen** [comment] 2019-12-19 15:09
@cbinder4 There is a browser cache present. You need to go to the show, click the poster and open the actual image in new tab (the url should be something like yourserver.com/showPoster/?show=331600&which=poster_thumb), then hit hard refresh (press browser refresh button while holding shift) and after that when you go to the listing you should see the image. Do the same for all the missing cover images.

**Comment by cbinder4** [comment] 2019-12-20 05:01
@ronilaukkarinen , yep, this extra step did it for me.  Thank you.

**Comment by miigotu** [comment] 2020-01-08 07:28
Completely fixed in develop branch. ;)

**Closed by miigotu** 2020-01-08 07:28 UTC

**Comment by hatemzidi** [comment] 2020-09-07 07:42
i'm may re-opening this issue, but i still have to copy the image into the thumbnail folder
i'm using : 

Branch: master
Commit: 64e55244d9bdc6d9012eaff214f3b254dc16df1f
Version: v2020.09.06-7
Database Version: 44.5
Python Version:3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by miigotu** [comment] 2020-09-07 21:02
@hatemzidi no log info?

**Comment by hatemzidi** [comment] 2020-09-08 09:09
@miigotu i got only this : 

```
2020-09-08 11:07:28 INFO :: WEBSERVER-HOME_0 :: Updating scene exceptions
2020-09-08 11:07:28 INFO :: WEBSERVER-HOME_0 :: Updating scene exceptions
```
