### ISSUE TITLE
Cant add new shows

### ISSUE THREAD

**Issue by kurtwarner** [SickChill/SickChill#5695] opened 2019-11-17 12:16 UTC
2019-11-17 11:46:28 SHOWQUEUE-ADD :: [e094759] Unable to look up the show in .... on theTVDB using ID 334622, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'es.xml' in the archive"
2019-11-17 11:46:20 SHOWQUEUE-ADD :: [e094759] Unable to look up the show in .... on theTVDB using ID 275274, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'es.xml' in the archive"

**Comment by mikey0613** [comment] 2019-11-17 12:22
Getting the same error here.. only with 'en.xml' .

**Comment by cadmuslabslex** [comment] 2019-11-17 13:50
I am also getting the same error. It was working fine up until last week I reinstalled from scratch, I get this error. 

2019-11-17 08:44:54 SHOWQUEUE-ADD :: [e094759] Unable to look up the show in D:\ShowExamples\showname on theTVDB using ID XXXXXX, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"
            
It doesnt matter if there is or isnt a nfo file in there, it wont add from imdb, thetvdb or any of the searchers. Please someone look at this.

**Comment by sjorge** [comment] 2019-11-17 15:06
This reported as #5686

**Comment by WebSpider** [comment] 2019-11-18 11:08
Duplicate of #5686

**Closed by WebSpider** 2019-11-18 11:08 UTC
