### ISSUE TITLE
mako error on show list only

### ISSUE THREAD

**Issue by amzeus1976** [SickChill/SickChill#6869] opened 2020-10-25 14:35 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:pip/master
OS:windows 10
Browser: chrome

What you did: update to python3 and the new version everything else working as intendeed but when clicking show list i get a Mako error. tried a clean install looks fine till i add my shows etc then the error happens just the same

What happened: Make Error
Traceback (most recent call last):
File c:\users\amzeu\appdata\local\programs\python\python39\lib\site-packages\sickchill\views\common.py:84, in render:
return self.template.render_unicode(*args, **context)
File c:\users\amzeu\appdata\local\programs\python\python39\lib\site-packages\mako\template.py:481, in render_unicode:
return runtime._render(
File c:\users\amzeu\appdata\local\programs\python\python39\lib\site-packages\mako\runtime.py:878, in _render:
_render_context(
File c:\users\amzeu\appdata\local\programs\python\python39\lib\site-packages\mako\runtime.py:920, in _render_context:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File c:\users\amzeu\appdata\local\programs\python\python39\lib\site-packages\mako\runtime.py:947, in _exec_template:
callable_(context, *args, **kwargs)
File c:/users/amzeu/appdata/local/programs/python/python39/lib/site-packages/sickchill/gui/slick/views/layouts/main.mako:325, in render_body:

What you expected: showing show list
Logs:
[sickchill.log](https://github.com/SickChill/SickChill/files/5434910/sickchill.log)

```
PASTE LOGS HERE
```

**Comment by amzeus1976** [comment] 2020-10-25 14:36
👍 

> Issue-Label Bot is automatically applying the label `Bug / Issue` to this issue, with a confidence of 0.94. Please mark this comment with 👍 or 👎 to give our bot feedback!
> 
> Links: [app homepage](https://github.com/marketplace/issue-label-bot), [dashboard](https://mlbot.net/data/SickChill/SickChill) and [code](https://github.com/hamelsmu/MLapp) for this bot.
👍

**Comment by nydave69** [comment] 2020-11-13 19:28
I have the same issue all of a sudden....

`Traceback (most recent call last):
                    File C:\SickChill\SickChill\sickchill\views\common.py:84, in render:
                        return self.template.render_unicode(*args, **context)
                    File C:\SickChill\SickChill\lib3\mako\template.py:481, in render_unicode:
                        return runtime._render(
                    File C:\SickChill\SickChill\lib3\mako\runtime.py:878, in _render:
                        _render_context(
                    File C:\SickChill\SickChill\lib3\mako\runtime.py:920, in _render_context:
                        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
                    File C:\SickChill\SickChill\lib3\mako\runtime.py:947, in _exec_template:
                        callable_(context, *args, **kwargs)
                    File C:/SickChill/SickChill/sickchill/gui/slick/views/layouts/main.mako:325, in render_body:`

`File C:/SickChill/SickChill/sickchill/gui/slick/views/home.mako:64, in render_content: <%include file="/inc_home_show_list.mako" args="curListType=curShowlist[0], myShowList=curShowlist[1]"/> File C:\SickChill\SickChill\lib3\mako\runtime.py:795, in _include_file: callable_(ctx, **kwargs) File C:/SickChill/SickChill/sickchill/gui/slick/views/inc_home_show_list.mako:168, in render_body: ${sbdatetime.sbdatetime.sbfdate(airDate)} File C:\SickChill\SickChill\lib3\dateutil\tz\tz.py:222, in utcoffset: if self._isdst(dt): File C:\SickChill\SickChill\lib3\dateutil\tz\tz.py:291, in _isdst: dstval = self._naive_is_dst(dt) File C:\SickChill\SickChill\lib3\dateutil\tz\tz.py:260, in _naive_is_dst: return time.localtime(timestamp + time.timezone).tm_isdst OSError: [Errno 22] Invalid argument 
`
`
SickChill Configuration
  SickChill Info:
Branch: master
Commit: fd546a06e190fa2de993e9197891de2a79f31f70
Version: v2020.10.22-2
Database Version: 44.5

  Python Version:
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.1.1g 21 Apr 2020

  OS:
Windows-7-6.1.7601-SP1

  Locale:
en_US.cp1252


  User:
Plex

  Program Folder:
C:\SickChill\SickChill\sickchill

  Config File:
C:\Users\Plex\sickchill\config.ini

  Database File:
C:\Users\Plex\sickchill\sickchill.db

  Cache Folder:
C:\Users\Plex\sickchill\cache

  Log Folder:
C:\Users\Plex\sickchill\Logs
`

If you need anything else ask..
the      cache_dir      does not exist in my config.ini at all

**Comment by OvoNemaSmisla** [comment] 2020-11-15 22:12
I have similar issue.

After pulling the latest version from github and restoring my backup, 3 TV shows are not showing thumbnails.
If I try Preview Rename option for any of the 3 shows I get the following error with the only difference being the last line:
```
Traceback (most recent call last):
File /opt/sickchill/sickchill/views/index.py:185, in async_call:
return function(**kwargs)
File /opt/sickchill/sickchill/views/home.py:1500, in testRename:
show_obj.getAllEpisodes(has_location=True)
File /opt/sickchill/sickchill/tv.py:209, in getAllEpisodes:
cur_ep = self.getEpisode(cur_result["season"], cur_result["episode"])
File /opt/sickchill/sickchill/tv.py:270, in getEpisode:
ep = TVEpisode(self, season, episode)
File /opt/sickchill/sickchill/tv.py:1309, in __init__:
self.specifyEpisode(self.season, self.episode)
File /opt/sickchill/sickchill/tv.py:1434, in specifyEpisode:
sql_results = self.loadFromDB(season, episode)
File /opt/sickchill/sickchill/tv.py:1491, in loadFromDB:
self.location = os.path.normpath(sql_results[0]["location"])
File /opt/sickchill/sickchill/tv.py:1347, in _set_location:
if new_location and os.path.isfile(new_location):
File /usr/lib/python3.6/genericpath.py:30, in isfile:
st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
```

Here is additional info from the log file:
```
2020-11-15 22:31:55 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
2020-11-15 22:32:57 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\xe9' in position 80: ordinal not in range(128)
2020-11-15 22:33:04 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
```


  SickChill Info:
Branch: master
Commit: fd546a06e190fa2de993e9197891de2a79f31f70
Version: v2020.10.22-2
Database Version: 44.2

  Python Version:
3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]

  SSL Version:
OpenSSL 1.1.1g 21 Apr 2020

  OS:
Linux-4.9.230-76-aarch64-with-Ubuntu-18.04-bionic

  Locale:
None.None


  User:
sickchill

  Program Folder:
/opt/sickchill/sickchill

  Config File:
/opt/sickchill/config.ini

  Database File:
/opt/sickchill/sickchill.db

  Cache Folder:
/opt/sickchill/cache

  Log Folder:
/opt/sickchill/Logs

  Arguments:
['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickchill']

**Comment by nydave69** [comment] 2020-11-21 12:47
does anyone have a temporary fix for this problem.

**Comment by amzeus1976** [comment] 2020-11-21 17:03
Did a pull to latest but no improvements

**Comment by Quarnof** [comment] 2020-12-13 23:02
seems to occur whenever you change from poster view.  if you revert the config.ini to poster under gui, it fixes it.  At least it did for me.

**Comment by OvoNemaSmisla** [comment] 2020-12-14 21:38
@Quarnof can you tell us what exact entry under gui section did you change and to what value?

Here is the gui part in my config.ini:
```
[GUI]
  gui_name = slick
  language = ""
  theme_name = dark
  sickchill_background = 0
  sickchill_background_path = ""
  fanart_background = 1
  fanart_background_opacity = 0.4
  custom_css = 0
  custom_css_path = ""
  home_layout = poster
  history_layout = detailed
  history_limit = 100
  display_show_specials = 1
  coming_eps_layout = banner
  coming_eps_display_paused = 0
  coming_eps_display_snatched = 0
  coming_eps_sort = date
  coming_eps_missed_range = 7
  fuzzy_dating = 0
  trim_zero = 0
  date_preset = %x
  time_preset = %I:%M:%S %p
  timezone_display = local
  poster_sortby = name
  poster_sortdir = 1
```

**Comment by Quarnof** [comment] 2020-12-14 22:09
so, what I had to do was stop sickchill, change home_layout = poster to home_layout = simple then start it up.  you will still have the mako error.  then repeat the process, but change it back to home_layout = poster.  when you start again, it will start working.  not sure why you have to change it and change it back, but that is what worked for me.

**Comment by OvoNemaSmisla** [comment] 2020-12-14 23:39
Thanks for the info, but it didn't work for me.

**Comment by nydave69** [comment] 2021-03-01 17:15
Any update on this?

**Comment by miigotu** [comment] 2021-03-01 23:43
> I have similar issue.
> 
> After pulling the latest version from github and restoring my backup, 3 TV shows are not showing thumbnails.
> If I try Preview Rename option for any of the 3 shows I get the following error with the only difference being the last line:
> ```
> Traceback (most recent call last):
> File /opt/sickchill/sickchill/views/index.py:185, in async_call:
> return function(**kwargs)
> File /opt/sickchill/sickchill/views/home.py:1500, in testRename:
> show_obj.getAllEpisodes(has_location=True)
> File /opt/sickchill/sickchill/tv.py:209, in getAllEpisodes:
> cur_ep = self.getEpisode(cur_result["season"], cur_result["episode"])
> File /opt/sickchill/sickchill/tv.py:270, in getEpisode:
> ep = TVEpisode(self, season, episode)
> File /opt/sickchill/sickchill/tv.py:1309, in __init__:
> self.specifyEpisode(self.season, self.episode)
> File /opt/sickchill/sickchill/tv.py:1434, in specifyEpisode:
> sql_results = self.loadFromDB(season, episode)
> File /opt/sickchill/sickchill/tv.py:1491, in loadFromDB:
> self.location = os.path.normpath(sql_results[0]["location"])
> File /opt/sickchill/sickchill/tv.py:1347, in _set_location:
> if new_location and os.path.isfile(new_location):
> File /usr/lib/python3.6/genericpath.py:30, in isfile:
> st = os.stat(path)
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> ```
> 
> Here is additional info from the log file:
> ```
> 2020-11-15 22:31:55 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> 2020-11-15 22:32:57 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\xe9' in position 80: ordinal not in range(128)
> 2020-11-15 22:33:04 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> ```
> 
> 
>   SickChill Info:
> Branch: master
> Commit: fd546a06e190fa2de993e9197891de2a79f31f70
> Version: v2020.10.22-2
> Database Version: 44.2
> 
>   Python Version:
> 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
> 
>   SSL Version:
> OpenSSL 1.1.1g 21 Apr 2020
> 
>   OS:
> Linux-4.9.230-76-aarch64-with-Ubuntu-18.04-bionic
> 
>   Locale:
> None.None
> 
> 
>   User:
> sickchill
> 
>   Program Folder:
> /opt/sickchill/sickchill
> 
>   Config File:
> /opt/sickchill/config.ini
> 
>   Database File:
> /opt/sickchill/sickchill.db
> 
>   Cache Folder:
> /opt/sickchill/cache
> 
>   Log Folder:
> /opt/sickchill/Logs
> 
>   Arguments:
> ['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickchill']
> 

You need to set your locale to utf-8, https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/?amp=1
 and set this environment variable:
```
PYTHONIOENCODING=utf8
```

**Comment by miigotu** [comment] 2021-03-01 23:45
@nydave69 doesn't seem like you have your time zone set.

What is the output of
```python
python3 -c "import time; print(time.timezone);" 
```

**Comment by nydave69** [comment] 2021-03-02 15:43
When I posted,  I had uninstalled SickChill, restarted and installed the latest version..  Still get that mako error when trying to list the shows.

![image](https://user-images.githubusercontent.com/14140816/109673509-1aa5d400-7b44-11eb-95e9-9545b68e4a07.png)

**Comment by miigotu** [comment] 2021-03-02 16:59
You'll need to provide the path to python3..... Reinstalling doesn't fix system configuration issues...

**Comment by OvoNemaSmisla** [comment] 2021-03-03 09:08
> 
> 
> > I have similar issue.
> > After pulling the latest version from github and restoring my backup, 3 TV shows are not showing thumbnails.
> > If I try Preview Rename option for any of the 3 shows I get the following error with the only difference being the last line:
> > ```
> > Traceback (most recent call last):
> > File /opt/sickchill/sickchill/views/index.py:185, in async_call:
> > return function(**kwargs)
> > File /opt/sickchill/sickchill/views/home.py:1500, in testRename:
> > show_obj.getAllEpisodes(has_location=True)
> > File /opt/sickchill/sickchill/tv.py:209, in getAllEpisodes:
> > cur_ep = self.getEpisode(cur_result["season"], cur_result["episode"])
> > File /opt/sickchill/sickchill/tv.py:270, in getEpisode:
> > ep = TVEpisode(self, season, episode)
> > File /opt/sickchill/sickchill/tv.py:1309, in __init__:
> > self.specifyEpisode(self.season, self.episode)
> > File /opt/sickchill/sickchill/tv.py:1434, in specifyEpisode:
> > sql_results = self.loadFromDB(season, episode)
> > File /opt/sickchill/sickchill/tv.py:1491, in loadFromDB:
> > self.location = os.path.normpath(sql_results[0]["location"])
> > File /opt/sickchill/sickchill/tv.py:1347, in _set_location:
> > if new_location and os.path.isfile(new_location):
> > File /usr/lib/python3.6/genericpath.py:30, in isfile:
> > st = os.stat(path)
> > UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> > ```
> > 
> > 
> > Here is additional info from the log file:
> > ```
> > 2020-11-15 22:31:55 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> > 2020-11-15 22:32:57 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\xe9' in position 80: ordinal not in range(128)
> > 2020-11-15 22:33:04 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
> > ```
> > 
> > 
> > SickChill Info:
> > Branch: master
> > Commit: [fd546a0](https://github.com/SickChill/SickChill/commit/fd546a06e190fa2de993e9197891de2a79f31f70)
> > Version: v2020.10.22-2
> > Database Version: 44.2
> > Python Version:
> > 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
> > SSL Version:
> > OpenSSL 1.1.1g 21 Apr 2020
> > OS:
> > Linux-4.9.230-76-aarch64-with-Ubuntu-18.04-bionic
> > Locale:
> > None.None
> > User:
> > sickchill
> > Program Folder:
> > /opt/sickchill/sickchill
> > Config File:
> > /opt/sickchill/config.ini
> > Database File:
> > /opt/sickchill/sickchill.db
> > Cache Folder:
> > /opt/sickchill/cache
> > Log Folder:
> > /opt/sickchill/Logs
> > Arguments:
> > ['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickchill']
> 
> You need to set your locale to utf-8, https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/?amp=1
> and set this environment variable:
> 
> ```
> PYTHONIOENCODING=utf8
> ```

Thanks for the suggestions.
I've set up the locale:
```
localectl status
   System Locale: LANG=C.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
```
And the envirnoment variable by adding a line in `/etc/environment`:
```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/$
PYTHONIOENCODING="utf8"
```
I've restarted SickChill, but the problem is still there.
The 3 shows don't show thumbnails and if I try to Preview Rename I get this:
![image](https://user-images.githubusercontent.com/53155262/109781404-2d81dc80-7c08-11eb-86ae-a8437b3d1ffc.png)

**Comment by miigotu** [comment] 2021-03-03 13:08
After setting /etc/environment, you have to reboot the server

**Comment by miigotu** [comment] 2021-03-03 16:13
Also, just use the command "locale", `LC_CTYPE` needs to be unicode aware, `LC_CTYPE=en_US.UTF-8` for example.

**Comment by nydave69** [comment] 2021-03-03 20:10
> You'll need to provide the path to python3..... Reinstalling doesn't fix system configuration issues...

OK...  I did add the path..
Python3 is installed by SickChill..

I opened a command window in C:\SickChill\Python3
entered your command (didn't work)

I then tried;  python -c "import time; print(time.timezone);" 

![image](https://user-images.githubusercontent.com/14140816/109865850-92eac300-7c32-11eb-89f5-d8cdfc274249.png)

**Comment by OvoNemaSmisla** [comment] 2021-03-03 20:36
> 
> 
> After setting /etc/environment, you have to reboot the server

That did it. No issue with Preview Rename.

Thanks!

**Comment by miigotu** [comment] 2021-03-04 01:21
Also, for windows, see https://docs.python.org/3/using/windows.html#utf-8-mode

**Comment by nydave69** [comment] 2021-03-06 14:13
I took a look at that page,  I'm no programmer and don't know where to put that command.

Shouldn't the windows installer have set up the required parameters.
All was fine till about 3 or 4 updates ago..

**Comment by miigotu** [comment] 2021-03-06 20:50
Nothing changed about this in the last 6 months.

Adding an environment variable has nothing to do with being a programmer, it has to do with system administration. And if you can't handle system administration, you probably shouldn't be using this type of software. I mean, if you can't handle an environment variable, how can anyone expect you to set up a vpn 🙄

**Comment by nydave69** [comment] 2021-03-07 17:04
> Nothing changed about this in the last 6 months.
> 
> Adding an environment variable has nothing to do with being a programmer, it has to do with system administration. And if you can't handle system administration, you probably shouldn't be using this type of software. I mean, if you can't handle an environment variable, how can anyone expect you to set up a vpn

Really..
I did set the environment path and the utf-8..
which works for another application..
The python code installed by sickchill is sickchill specific.

Sickchill is the only application that I consistently have issues with. When I do get it to work it's only for a few months and then something changes again..

Why would one create a user specific application that doesn't work from the install?
As I have said,  I totally removed SickChill rebooted and reinstalled the latest version. 
It doesn't work from the install.  and I am not the only to report this issue. 
If you don't want to fix it just say so.

**Closed** 2021-03-07 18:16 UTC
Labels: Bug / Issue

**Comment by miigotu** [comment] 2021-03-07 18:21
Check your `settings.DATE_PRESET`, or the system default date preset. `Date style` in settings page.
