### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-313999 :: [7a26059] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by petemmitchell** [SickChill/SickChill#4377] opened 2018-03-12 06:05 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a26059801aed3e1aa4994663b0c68ee13fb3d56
Link to Log: https://gist.github.com/dd9ad27a081633714c3a5d23b2e5758e
### ERROR
```
SEARCHQUEUE-MANUAL-313999 :: [7a26059] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by petemmitchell** [comment] 2018-03-12 06:05
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7a26059801aed3e1aa4994663b0c68ee13fb3d56
Link to Log: https://gist.github.com/90f43f9b72f9c4a8eeaa77c0ff36e80d
### ERROR
```
SEARCHQUEUE-MANUAL-278518 :: [7a26059] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 22:49
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:49 UTC
