### ISSUE TITLE
SickChill Re-Downloading Episodes Due To Status Resets

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#5464] opened 2019-05-08 19:59 UTC
SickChill has an issue where it will re-download episodes if various conditions are met.   (This usually happens if the show is from a streaming provider vs a broadcast one although that can still occur as well, just less likely.)

1. When SickChill updates show data for the day, this can sometimes - for various reasons - switch a show's status from aired/wanted to unaired.    This seems to clear the episode status.    This will cause a re-download because the episode status is effectively reset.

2. When SickChill flags new episodes as wanted, if the episode has already been marked as snatched or downloaded, it **resets** to wanted, this will cause a re-download.

A solution might be a conf flag to not change episode status from snatched/downloaded or archived.

**Comment by Torhal** [comment] 2019-05-21 00:45
I've had this happen to me twice, resulting in entire seasons of shows being downloaded long after I'd already had them marked as archived. The only cause I can think of is TheTVDB having a moderation war on said show, which flips the episode airdates/statuses causing SickChill to become confused as outlined in the above post.

**Comment by WebSpider** [comment] 2019-05-27 07:13
I've had this happen as well due to metadata changes

**Comment by NoemiNL** [comment] 2020-01-23 22:15
Happend here as well, this week even 3 times.

**Comment by fatgeek** [comment] 2020-03-08 16:28
This has been happening to me a lot in the past two weeks. It's happened with about 10 series and downloaded the entire run after they'd been archived for years. This is especially troubling for me since I'm under a bandwidth cap.

**Comment by ryangribble** [comment] 2020-03-10 09:59
Yes I just came on here to search for similar problems... the last week SickChill has suddenly strted to download LOADS of prior episodes.  At first it seemed it may have been ones that were Archived, so i force changed them all to Skipped status.  Things seemed OK for a while, then suddenly a bunch of shows were in the Backlog search again, seemingly because they were "Downloaded (Unknown)" and that didnt match the desired quality.  So I then turned on this option in Search Settings: "Backlog search for missing only - restrict backlog searches to missing episodes only?"

My backlog overview screen was showing very few things and all of which were legitimately missed...

Then today I see SickChill has queued up over 100 old episodes of American Dad, Inside Amy Schumer and The Strain.  I can't tell what the status of these were previously but they are all set to Wanted status now.

**Comment by jonand** [comment] 2020-03-15 09:57
This has happened to me a few times during the last weeks. I've downloaded several TB of old seasons. This is really hurting my ratio so please prioritise fixing this bug!

Episodes are going from Archived to Wanted and then entire old seasons are being downloaded again. I tried setting them all to Skipped but I believe a few of them were still being downloaded again. Now I've tried setting them all to Ignored.

**Comment by Ackman999** [comment] 2020-03-15 10:27
This is still an issue, has anyone found a solution for this?

**Comment by jonand** [comment] 2020-03-16 17:57
Another five seasons of unwanted TV series downloaded today! Previous state ignored.

I've now paused all not currently active series to reduce the risk of this happening. Any other suggestions on how to limit the damage?

**Comment by knelmes** [comment] 2020-03-16 18:10
Is there a way to set the start state to paused? I've had a look through the settings and can only find a setting to make it forced. 
I think I'd rather have to OK everything rather than have it download 10 seasons of bluray remuxes like it tried to this morning. Only caught it because I woke up early and it'd only done 3 episodes.

**Comment by nickoo0** [comment] 2020-03-16 18:23
same issue here, downloaded 130GB of old shows I had already downloaded.

here is a small amount

```
2020-03-16 09:13:51 INFO SEARCHQUEUE-BACKLOG- :: Sending NZB to SABnzbd
2020-03-16 09:13:51 INFO SEARCHQUEUE-BACKLOG- :: Downloading Running.Wild.with.Bear.Grylls.S05E10.720p.HDTV.x264-CROOKS-xpost from nzb.su
2020-03-16 09:13:49 INFO SEARCHQUEUE-BACKLOG- :: Sending NZB to SABnzbd
2020-03-16 09:13:49 INFO SEARCHQUEUE-BACKLOG- :: Downloading Running.Wild.with.Bear.Grylls.S05E09.720p.HDTV.x264-CROOKS-xpost from nzb.su
2020-03-16 09:13:46 INFO SEARCHQUEUE-BACKLOG- :: Sending NZB to SABnzbd
2020-03-16 09:13:46 INFO SEARCHQUEUE-BACKLOG- :: Downloading Running.Wild.with.Bear.Grylls.S05E08.720p.HDTV.x264-CROOKS-xpost from nzb.su
2020-03-16 09:13:43 INFO SEARCHQUEUE-BACKLOG- :: Sending NZB to SABnzbd
2020-03-16 09:13:43 INFO SEARCHQUEUE-BACKLOG- :: Downloading Running.Wild.with.Bear.Grylls.S05E07.720p.HDTV.x264-CROOKS-xpost from nzb.su
2020-03-16 09:13:41 INFO SEARCHQUEUE-BACKLOG- :: Sending NZB to SABnzbd
```

**Comment by Wally73** [comment] 2020-03-16 19:10
set your backlog lookup (config/search/) higher then 720 minutes (12 hours)
and check backlog overview

(or pause your downloader during the night and check it when you awake
again)

**Comment by knelmes** [comment] 2020-03-16 19:46
Good plan for now, thanks

**Comment by pixilarion** [comment] 2020-03-17 05:31
I had the same problem here twice, causing a redownload of already downloaded/watched/archived episodes. This really hurts my download volume limit (yep, we still have those), so a fix would be much appreceated. For some reason with me it only seems to happen when watchtower updates my sickchill docker container.

**Comment by nydave69** [comment] 2020-03-17 14:11
I paused the back log queue.....

**Comment by johan-adriaans** [comment] 2020-03-17 17:12
Same here, this is where the show Victoria got reset, no errors in the log.

```
2020-03-13 05:44:01 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Marcella
2020-03-13 05:44:01 INFO     SHOWQUEUE-REFRESH :: 308986: Updating NFOs for show with new indexer info
2020-03-13 05:44:06 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Victoria
2020-03-13 05:44:06 INFO     SHOWQUEUE-REFRESH :: 302205: Updating NFOs for show with new indexer info
2020-03-13 05:44:11 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Vera
2020-03-13 05:44:11 INFO     SHOWQUEUE-REFRESH :: 248393: Updating NFOs for show with new indexer info
```

There was 1 error during the daily search, seems unrelated but you never know:
```
2020-03-13 06:22:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [4d0657e] Request failed: !!Loop Protection!! We have tried to solve 3 time(s) in a row. (<type 'str'>)
Traceback (most recent call last):
Cloudflare_Loop_Protection: !!Loop Protection!! We have tried to solve 3 time(s) in a row.
```

Later that day it starts the backlog search and started to download all 3 seasons, but not the specials.
```
2020-03-13 10:55:37 INFO     SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [Victoria]
```

Status was 'downloaded' before the 13th, no changes were made to any quality settings. If you need more logs, let me know.

**Comment by leha007** [comment] 2020-03-17 17:13
Same issue here, 121GB of bandwidth wasted...

**Comment by darienfawk** [comment] 2020-04-09 19:17
Same issue here. 2 shows downloading all the time, it doesnt matter if was set to wanted, archived, snatched... It gets pretty annoying. Deleting couple dozens episodes each day.

**Comment by scottfreeze** [comment] 2020-04-10 13:27
This Issue was marked as Confirmed last May.  Any chance of getting an update on the status?  I also just had an entire series re-download.

**Comment by leha007** [comment] 2020-04-10 17:18
I know it's open source and free to use but this is critical bug. Have switched to radarr docker, zero issues until now.

**Comment by nickoo0** [comment] 2020-04-13 08:47
just happened again last night, red dwarf reset itself back to wanted that is a show with 12 series. Thankfully I changed the backlog frequency as mentioned above so noticed before it tried to re-download the whole 12 series. Kind of annoying as I have to now manually check the backlog each day to ensure there are no issues. Appreciate this is free software btw ;)

**Comment by miigotu** [comment] 2020-04-20 10:24
This should have settled down. It definitely happens because of tvdb issues on their end, but we can prevent it somehow in our code. Please open a new issue and link this issue from it when you have it happen again.

**Closed by miigotu** 2020-04-20 10:24 UTC
Labels: Bug / Issue, Confirmed
