### ISSUE TITLE
Checking poetry makes SC fail and exit

### ISSUE THREAD

**Issue by luisfcorreia** [SickChill/SickChill#8137] opened 2022-09-01 21:59 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
git log
commit b2b09e3720a5e1b4af3d88a165fa8f97d0a44593 (HEAD -> master, tag: 2022.8.30, origin/master, origin/HEAD)

OS: Fedora Linux 36
Browser: irrelevant
What you did: started the process
What happened: it failed
What you expected: working
Logs:
```
Checking poetry
Can write to /home/sickchill/.local/lib/python3.10/site-packages: True
Can write to /opt/sickchill/.venv/lib64/python3.10/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
["No module named 'poetry_date_version_plugin'"]
Unable to install to the existing virtual environment located at /opt/sickchill/.venv
Please check the permissions, and that it does not include global site packages

```

**Comment by kyuuk** [comment] 2022-09-01 22:02
duplicate of #8126 

please check open issues before opening a new one 😄

**Closed by kyuuk** 2022-09-01 22:02 UTC

**Comment by luisfcorreia** [comment] 2022-09-01 22:07
I'm sorry it is NOT a duplicate, it's a SIMILAR problem

Maybe both get to be fixed but my system isn't working a this moment

**Comment by kyuuk** [comment] 2022-09-01 22:44
it seems that you environment is kinda broken if SC can't install to it's own .venv 

did you try to install the module manually, 
`/opt/sickchill/.venv/bin/python3.10 -m pip install poetry_date_version_plugin`

**Comment by luisfcorreia** [comment] 2022-09-01 22:46
Isn't that a thing SC should take care of?
I removed several times .venv to try and refresh it to no avail

**Comment by kyuuk** [comment] 2022-09-01 23:00
that actually is the issue i mentioned earlier(that poetry isn't installing this module), and  it's being worked on.

i also have the same problem, and all i can do is install it manually

**Comment by luisfcorreia** [comment] 2022-09-02 08:08
Thanks,
I can accept that answer with any reserve.

**Comment by nydave69** [comment] 2022-09-02 15:07
OS:  Windows 10
How am I to know what packages SickChill requires? If it won't be installing them...

**Comment by miigotu** [comment] 2022-09-18 19:35
On windows 
```cmd
net stop sickchill 
c:\SickChill\Python3\Tools\pip.exe install -U sickchill
net start sickchill 
```

**Comment by miigotu** [comment] 2022-09-18 19:38
Poetry should not be used by end users. There was some confusion with what to tell users and who should be using poetry or not (poetry is for development, just use pip and venv) but check this wiki page about updating, and use search for other issues related to pip. Source and git based installs will not self update anymore.

 https://github.com/sickchill/sickchill/wiki/pip
