### ISSUE TITLE
Missing Node.js runtime and error whilst submitting

### ISSUE THREAD

**Issue by IamC8** [SickChill/SickChill#4322] opened 2018-02-19 16:13 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Master
OS:Linux
What you did:Trying to submit issue of Missing Node.js runtime
What happened: Submit also produce error
What you expected: Error being submitted
Logs:
```
2018-02-19 11:10:10 SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [5066fab] Request failed: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
2018-02-19 11:09:38 SEARCHQUEUE-BACKLOG-328708 :: [Torrent9] :: [5066fab] Request failed: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
2018-02-19 11:07:52 Thread-474 :: [5066fab] Traceback (most recent call last):
File "/opt/sickrage/sickbeard/logger.py", line 332, in submit_errors
if LOGGING_LEVELS[level] == ERROR:
KeyError: u'2018-02-19 11:07:14'

2018-02-19 11:07:14 Thread-474 :: [5066fab] Traceback (most recent call last):
File "/opt/sickrage/sickbeard/logger.py", line 332, in submit_errors
if LOGGING_LEVELS[level] == ERROR:
KeyError: u'2018-02-19 11:05:32'

2018-02-19 11:05:32 SEARCHQUEUE-BACKLOG-287314 :: [Torrent9] :: [5066fab] Request failed: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
2018-02-19 11:01:50 SEARCHQUEUE-BACKLOG-321060 :: [Torrent9] :: [5066fab] Request failed: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
```

**Comment by claytondukes** [comment] 2018-02-22 02:15
This duplicates #4323

**Comment by claytondukes** [comment] 2018-02-22 02:27
Installing nodejs seems to fix it (so far):
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by WebSpider** [comment] 2018-12-02 22:44
Duplicate of #4323

**Closed by WebSpider** 2018-12-02 22:44 UTC
