### ISSUE TITLE
[APP SUBMITTED]: Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/349309/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x704d78f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/349309/en.xml

### ISSUE THREAD

**Issue by dporem** [SickChill/SickChill#5704] opened 2019-11-19 10:40 UTC
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/349309/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x704d78f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/349309/en.xml
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment] 2019-11-19 13:55
The tvdb has a whole bunch of issues atm, closing this as duplicate of #5686

**Closed by WebSpider** 2019-11-19 13:55 UTC
