### ISSUE TITLE
Sickchill on docker does not start with error "Cannot set verify_mode to CERT_NONE when check_hostname is enabled."

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#8101] opened 2022-08-22 17:28 UTC
Branch/Commit: master
OS: Docker
i just updated the docker image to the latest master tag, and sickchill does not start anymore 
it's just a guess but i think it from this [commit ](https://github.com/SickChill/SickChill/commit/94d25cb3c7ba6d2f62629cba77343cad2c2e2b82) and this [param](https://github.com/SickChill/SickChill/blob/94d25cb3c7ba6d2f62629cba77343cad2c2e2b82/sickchill/start.py#L211) if it's set to false

Logs:
```
Traceback (most recent call last):
  File "/app/sickchill/SickChill.py", line 350, in <module>
    main()
  File "/app/sickchill/SickChill.py", line 345, in main
    SickChill().start()
  File "/app/sickchill/SickChill.py", line 151, in start
    sickchill.start.initialize(consoleLogging=self.console_logging)
  File "/app/sickchill/sickchill/start.py", line 212, in initialize
    helpers.set_opener(settings.SSL_VERIFY)
  File "/app/sickchill/sickchill/oldbeard/helpers.py", line 71, in set_opener
    https_handler = HTTPSHandler(context=make_context(verify), check_hostname=verify)
  File "/app/sickchill/sickchill/oldbeard/helpers.py", line 62, in make_context
    context.verify_mode = ssl.CERT_REQUIRED if verify else ssl.CERT_NONE
  File "/usr/local/lib/python3.9/ssl.py", line 721, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```
if anyone have the same probleme 
workaround : edit the config.ini search for `ssl_verify` and set the value to `1`
![image](https://user-images.githubusercontent.com/16566073/185982652-cf244970-3d9b-4f2e-afab-202a9c0ffbda.png)

**Comment by miigotu** [comment] 2022-08-22 21:31
Or update to the latest docker image or git pull inside the container. It's already fixed in the release from last night.

**Comment by miigotu** [comment] 2022-08-22 21:32
The commit you referenced if the fix for the bug btw, not the cause.

**Comment by felixbrucker** [comment] 2022-08-23 15:05
I have the same issue and it was not fixed with the latest docker image, the workaround mentioned worked tho

**Comment by kyuuk** [comment] 2022-08-23 19:19
Hello,
as you can see @miigotu it's already the latest image 
![image](https://user-images.githubusercontent.com/16566073/186245960-f937d9c4-0d09-45b3-aa22-2db4b7a8de73.png)

maybe that fix broke something else (i'm not good enough to be sure), again it's just a guess

**Comment by miigotu** [comment] 2022-08-23 19:47
I'm going to rewrite how that works later. It's legacy code to begin with and we should always be verifying the hostname anyway. We can disable it on a provider by provider basis instead.

**Closed** 2022-08-29 22:03 UTC
