### ISSUE TITLE
[APP SUBMITTED]: [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E22 - \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe5\x89\x8d\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x88\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x83\x86\xe3\x83\x8b\xe3\x82\xb9\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe6\xb2\xbb\xe9\xa8\x93\xe3\x83\x90\xe3\x82\xa4\xe3\x83\x88\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe5\x85\x

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4876] opened 2018-08-14 12:54 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/d9885cd299d37a8d60842e6e1fdbe21b
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E22 - \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe5\x89\x8d\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x88\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x83\x86\xe3\x83\x8b\xe3\x82\xb9\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe6\xb2\xbb\xe9\xa8\x93\xe3\x83\x90\xe3\x82\xa4\xe3\x83\x88\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe5\x85\x8d\xe8\xa8\xb1\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe7\x85\xa7\xe6\xa9\x8b\xe3\x83\x87\xe3\x83\xbc\xe3\x83\x88\xe7\xb7\xa8 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 12:54
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/f7fc33002e3f782c28422e225259302e
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 22 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E22 - 夏休み前のΨ難 夏休み真っΨ中！オカルト部合宿編／夏休み真っΨ中！テニス部合宿編／夏休み真っΨ中！治験バイト編／夏休み真っΨ中！免許合宿編／夏休み真っΨ中！照橋デート編 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 16:50
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/bec8d906a9068aaddf34f8a9999eb347
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E22 - \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe5\x89\x8d\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x88\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x83\x86\xe3\x83\x8b\xe3\x82\xb9\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe6\xb2\xbb\xe9\xa8\x93\xe3\x83\x90\xe3\x82\xa4\xe3\x83\x88\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe5\x85\x8d\xe8\xa8\xb1\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe7\x85\xa7\xe6\xa9\x8b\xe3\x83\x87\xe3\x83\xbc\xe3\x83\x88\xe7\xb7\xa8 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 16:51
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/0b6880e60c327fa6453921d45faadbec
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 22 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E22 - 夏休み前のΨ難 夏休み真っΨ中！オカルト部合宿編／夏休み真っΨ中！テニス部合宿編／夏休み真っΨ中！治験バイト編／夏休み真っΨ中！免許合宿編／夏休み真っΨ中！照橋デート編 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:14
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/2d3680b5002d0d28b7842160892fe0ec
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E22 - \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe5\x89\x8d\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 \xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x82\xaa\xe3\x82\xab\xe3\x83\xab\xe3\x83\x88\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe3\x83\x86\xe3\x83\x8b\xe3\x82\xb9\xe9\x83\xa8\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe6\xb2\xbb\xe9\xa8\x93\xe3\x83\x90\xe3\x82\xa4\xe3\x83\x88\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe5\x85\x8d\xe8\xa8\xb1\xe5\x90\x88\xe5\xae\xbf\xe7\xb7\xa8\xef\xbc\x8f\xe5\xa4\x8f\xe4\xbc\x91\xe3\x81\xbf\xe7\x9c\x9f\xe3\x81\xa3\xce\xa8\xe4\xb8\xad\xef\xbc\x81\xe7\x85\xa7\xe6\xa9\x8b\xe3\x83\x87\xe3\x83\xbc\xe3\x83\x88\xe7\xb7\xa8 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:14
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/b630746fb9b01cff9b828a74d06bf191
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to link file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 22 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E22 - 夏休み前のΨ難 夏休み真っΨ中！オカルト部合宿編／夏休み真っΨ中！テニス部合宿編／夏休み真っΨ中！治験バイト編／夏休み真っΨ中！免許合宿編／夏休み真っΨ中！照橋デート編 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:37
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 22 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E22 - 夏休み前のΨ難 夏休み真っΨ中！オカルト部合宿編／夏休み真っΨ中！テニス部合宿編／夏休み真っΨ中！治験バイト編／夏休み真っΨ中！免許合宿編／夏休み真っΨ中！照橋デート編 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-11-30 17:21
Duplicate of #4868

**Closed by WebSpider** 2018-11-30 17:21 UTC
