### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-279121 :: [5bc5c3a] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by MotleyC** [SickChill/SickChill#4271] opened 2018-01-25 12:08 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [5bc5c3a] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment] 2018-01-25 12:09
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295759 :: [5bc5c3a] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment] 2018-02-05 04:20
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5bc5c3a] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment] 2018-02-05 22:38
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5bc5c3a] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 22:50
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:50 UTC
