### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: [807c5ae] Multiple entries for absolute number: 4 in show: Daria found 

### ISSUE THREAD

**Issue by Gendefekt** [SickChill/SickChill#4787] opened 2018-06-17 10:35 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [807c5ae] Multiple entries for absolute number: 4 in show: Daria found 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 03:14
Duplicate of #4767

**Closed by WebSpider** 2018-12-02 03:14 UTC
Labels: Duplicate
