### ISSUE TITLE
ReadyNAS error searching IPTorrents

### ISSUE THREAD

**Issue by horganhoozen** [SickChill/SickChill#5638] opened 2019-09-26 12:20 UTC
Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Database Version: 44.0
OS: ReadyNAS
What you did: Perform Backlog Search
What happened: Errors Happened
What you expected: No Errors
Logs:
```
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "/apps/sickchill/sickbeard/helpers.py", line 1523, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "/apps/sickchill/sickbeard/helpers.py", line 1579, in handle_requests_exception
AA handle_requests_exception(error)
AA File "/apps/sickchill/sickbeard/helpers.py", line 1466, in getURL
AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
AA File "/apps/sickchill/sickchill/providers/GenericProvider.py", line 374, in get_url
AA data = self.get_url(search_url, returns='text')
AA File "/apps/sickchill/sickbeard/providers/iptorrents.py", line 131, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/apps/sickchill/sickchill/providers/GenericProvider.py", line 170, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/apps/sickchill/sickbeard/search.py", line 474, in searchProviders
```

**Comment by horganhoozen** [comment] 2019-09-26 12:39
I was able to do a workaround by implementing the change mentioned in Issue #5185 
but this needs to be fixed as after every commit update I have to update the file again

**Comment by trick77** [comment] 2019-11-03 14:52
I'm seeing the same error. What workaround is working for you? I only see automated bug reports in 5185.

**Comment by trick77** [comment] 2019-11-03 14:59
Ah, found it after loading all the hidden comments:
https://github.com/SickChill/SickChill/issues/5423

So the issue is in the cfscrape lib :(

**Comment by trick77** [comment] 2019-11-03 15:01
And after reading https://github.com/SickChill/SickChill/issues/5423#issuecomment-493799763 I'm going to disable nodejs for SickChill.

**Comment by dci2112** [comment] 2019-11-21 13:40
This is also happening to me on my QNAP. Hoping for a permanent fix so updates don't break this.

**Comment by miigotu** [comment] 2020-01-11 16:15
Fixed in develop

**Closed by miigotu** 2020-01-11 16:15 UTC
