### ISSUE TITLE
Fetching of IMDB Data failed. Are you online? Exception:

### ISSUE THREAD

**Issue by warrenmunitz** [SickChill/SickChill#6186] opened 2020-04-09 18:00 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by warrenmunitz** [comment] 2020-04-09 18:00
I can't add new IMDB shows. I just get this error:
Fetching of IMDB Data failed. Are you online? Exception:

**Comment by Drsela** [comment] 2020-04-11 19:36
I'm experiencing the same:

Branch/Commit: Master
OS: Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64
Browser: Microsoft Edge 83.0.474.0
What you did: Clicked 'Shows' -> clicked 'Add Shows' --> clicked 'Add From IMDB's Popular Shows'
What happened: The UI gives me the following error: Fetching of IMDB Data failed. Are you online? Exception: None
What you expected: To see shows from iMDB
Logs: 
`2020-04-11 21:29:00 INFO WEBSERVER-ADDSHOWS :: Request failed: HTTPConnectionPool(host='akas.imdb.com', port=80): Max retries exceeded with url: /search/title?sort=moviemeter&title_type=tv_series&at=0&year=2019%2C2021 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',)) ()
`

**Comment by uMag** [comment] 2020-04-12 09:13
Have same issue, added akas.imdb.com 52.94.225.248 to hosts file and fixed that.
imdb turned off akas endpoint and same info served from main site

**Comment by warrenmunitz** [comment] 2020-04-12 09:57
I have no idea how to do that?

Warm Regards
*Warren Munitz* - *Master Coach, Author & **Founder*
+27 (0) 82 377-1994 | +27 (0) 21 418-5080
*Click for Directions <https://goo.gl/maps/1gkXF> - *First Floor, 49A
Somerset Road, Green Point, Cape Town <https://goo.gl/maps/1gkXF>

*Join Us On*
Facebook <http://www.integrativecoaching.co.za/Facebook>
YouTube <http://www.integrativecoaching.co.za/YouTube>
Instagram <https://www.instagram.com/warrenmunitz/>
Online Training
<https://www.integrativecoachingacademy.co.za/p/new-emotional-mastery-course>

**Comment by Drsela** [comment] 2020-04-12 10:08
The host file is usually located at `/etc/hosts` on Linux and `C:\Windows\System32\drivers\etc` on Windows.  Just add a new line with the following: `akas.imdb.com 52.94.225.248`. This'll tell the server to use 52.94.225.248 as the ip address whenever you request info from akas.imdb.com.

**Comment by miigotu** [comment] 2020-04-13 04:01
Fixed in develop branch.

**Closed by miigotu** 2020-04-13 04:01 UTC

**Comment by idem2lyon** [comment] 2022-07-17 20:03
same issue here with last release of TrueNAS scale

**Comment by ghenry22** [comment] 2023-09-04 05:44
this is back again in the latest linux release...

**Comment by fergalmccarthy** [comment] 2023-09-12 20:16
same issue here the last month or so

**Comment by tobidoo** [comment] 2023-09-22 06:46
Same here on Unraid. Been like this for a month or two. Updated Sickchill today. Still same problem.

**Comment by miigotu** [comment] 2023-09-24 13:08
Has nothing to do with sickchill. Like I said, the Library that talks to IMDb is waiting on an update because the site changes and they don't have a real api

**Comment by dxs1** [comment] 2023-10-25 22:09
Hi

As recommended here, I have added IP in /etc/hosts (52.94.225.248   akas.imdb.com)
> ping akas.imdb.com
> PING akas.imdb.com (52.94.225.248) 56(84) bytes of data.
> 64 bytes from akas.imdb.com (52.94.225.248): icmp_seq=1 ttl=236 time=96.3 ms
> 64 bytes from akas.imdb.com (52.94.225.248): icmp_seq=2 ttl=236 time=97.9 ms
> 64 bytes from akas.imdb.com (52.94.225.248): icmp_seq=3 ttl=236 time=96.6 ms
> ^C
> --- akas.imdb.com ping statistics ---
> 4 packets transmitted, 3 received, 25% packet loss, time 3004ms
> rtt min/avg/max/mdev = 96.262/96.913/97.885/0.700 ms

Same issue occuring: "Fetching of IMDB Data failed. Are you online?"

> Has nothing to do with sickchill. Like I said, the Library that talks to IMDb is waiting on an update because the site changes and they don't have a real api

From the discussions I have read in links below, my guess is that this issue is related to how the python code manages foreign names of shows; and the sickchill issue occurs when the sickchill server is NOT located in the US
https://www.geeksforgeeks.org/python-imdbpy-getting-alternate-names-of-the-series/
https://community-imdb.sprinklr.com/conversations/imdbcom/akasimdbcom-https-certificate-is-not-valid-for-the-domain/5f4a79d18815453dba8c109a

Could this be the root cause to the issue in sickchill ?

**Comment by horstt** [comment] 2023-11-25 11:16
Same issue here, "Fetching of IMDB Data failed. Are you online?". Has been the case for months now. I'm also not based in the US.

**Comment by miigotu** [comment] 2023-11-25 22:08
https://github.com/SickChill/sickchill/issues/6186#issuecomment-1732567113
