### ISSUE TITLE
Some Automatic Subtitle search: TypeError: tuple indices must be integers or slices, not str'

### ISSUE THREAD

**Issue by IxFail** [SickChill/SickChill#8058] opened 2022-08-10 20:45 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch:** master
**Commit:** d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
**Version:** 2022.07.20
**Database Version:** 44.5
**Python Version:** 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0]
**SSL Version:** OpenSSL 1.1.1f 31 Mar 2020
**Locale:** en_US.UTF-8

**OS:** Ubuntu 20.04.4 LTS (Linux-5.4.0-122-generic-x86_64-with-glibc2.31)
**Browser:** Google Chrome 104.0.5112.81 64-bit
**What you did:** Open sickchill and saw multiple error in the loggin 
**What happened:** Logging indicated the following: the multiple error with Error: tuple indices must be integers or slices, not str
**What you expected:** no errors
**Extra:** When I looked in the media folder, the subtitle was downloaded but not shown in SickChill, I deleted the subtitle file in de media folder and did manual subtitle search, the subtitle was downloaded but not show in Sickchill (Little country flag, not even after a Re-scan)

The logs does not give more error details than what is show below(Like Tracebacks or some sort)

I saw #8051 and checked the file subtitles.py, on row 257 I got `                f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores.res}/{scores.percent}% (min={scores.min}/{scores.min_percent}%)"` (With all the spaces before it) just as it should

I Hope I gave enough information, if not please let met know.

Thanks

Logs:
```
2022-08-09 16:56:47 INFO :: FINDSUBTITLES :: Searching for missing subtitles of Chicago Fire S05E04
2022-08-09 16:56:47 DEBUG :: FINDSUBTITLES :: Checking subtitle candidates for Chicago Fire S05E04 (Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today.mkv)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: Could not search in podnapisi provider. Discarding for now
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1955368016 is: 771/48% (min=213/13%)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1955368015 is: 768/47% (min=213/13%)
2022-08-09 16:56:48 DEBUG :: FINDSUBTITLES :: [opensubtitles] Subtitle score for 1956518372 is: 768/47% (min=213/13%)
2022-08-09 16:56:48 ERROR :: FINDSUBTITLES :: Unable to find subtitles for Chicago Fire S05E04. Error: tuple indices must be integers or slices, not str
```

**Comment by bradysvbc** [comment] 2022-08-11 02:41
Getting same error as well on my system as well running Version: 2022.07.20.

**Comment by BKSteve** [comment] 2022-08-11 10:51
I can't reproduce this error with `English` subtitles only selected in settings
![image](https://user-images.githubusercontent.com/10173496/184117157-6f66d147-a7b6-4b52-8306-8ada4b9f63a2.png)

```
2022-08-11 17:39:54 INFO :: SHOWQUEUE-SUBTITLE :: Downloading subtitles for Chicago Fire 
2022-08-11 17:39:54 DEBUG :: SHOWQUEUE-SUBTITLE :: 258541: Downloading subtitles
2022-08-11 17:39:54 DEBUG :: SHOWQUEUE-SUBTITLE :: Checking subtitle candidates for Chicago Fire S05E04 (Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today.mkv)
2022-08-11 17:39:59 DEBUG :: SHOWQUEUE-SUBTITLE :: Unable to set <class 'subliminal.video.Episode'>.episode from episode.episode attribute
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956495278 is: 767/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362495 is: 773/48% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956498486 is: 361/22% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956223071 is: 766/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956223070 is: 765/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362445 is: 765/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362446 is: 766/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956500558 is: 768/47% (min=213/13%)
2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956498481 is: 360/22% (min=213/13%)
2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: 258541: Downloaded English subtitles for Chicago Fire S05E04
2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: Parsed /home/stephenr/Videos/Chicago Fire/Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today into Chicago Fire - S05E04 [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: formatting pattern: %SN - S%0SE%0E - %EN -> Chicago Fire - S05E04 - Nobody Else Is Dying Today
```

**Comment by ronrosenfeld** [comment] 2022-08-11 11:44
I, too, have been seeing this error recently

```
Install: pip
Version: v2022.07.20
Database Version: 44.2


2022-08-10 04:39:46 INFO :: CHECKVERSION :: Checking for updates using PIP
2022-08-10 04:49:46 INFO :: FINDSUBTITLES :: Checking for missed subtitles
2022-08-10 04:49:46 INFO :: FINDSUBTITLES :: Searching for missing subtitles of Hacks (2021) S01E69
2022-08-10 04:49:47 INFO :: FINDSUBTITLES :: Error occurred when downloading subtitles for: F:\Videos\Hacks (2021)\S01E08\1.69 Million 1080p WEB-DL h264.mkv
2022-08-10 04:49:47 ERROR :: FINDSUBTITLES :: Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

2022-08-10 04:49:47 INFO :: FINDSUBTITLES :: Finished checking for missed subtitles
```

**Comment by IxFail** [comment] 2022-08-11 21:53
> I can't reproduce this error with `English` subtitles only selected in settings SickChill Info: Branch: [master](https://anonym.to/?https://github.com/SickChill/SickChill/tree/master) Commit: [d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5](https://anonym.to/?https://github.com/SickChill/SickChill/commit/d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5) Version: [2022.07.20](https://anonym.to/?https://github.com/SickChill/SickChill/releases/tag/2022.07.20) Database Version: 44.5 Python Version:3.10.5 (main, Jul 24 2022, 16:47:08) [GCC 10.2.1 20210110] SSL Version:OpenSSL 1.1.1n 15 Mar 2022 OS:Linux-5.10.0-16-amd64-x86_64-with-glibc2.31 `Debian 11` Version: [2022.07.20](https://anonym.to/?https://github.com/SickChill/SickChill/releases/tag/2022.07.20)
> 
> ![image](https://user-images.githubusercontent.com/10173496/184117157-6f66d147-a7b6-4b52-8306-8ada4b9f63a2.png)
> 
> ```
> 2022-08-11 17:39:54 INFO :: SHOWQUEUE-SUBTITLE :: Downloading subtitles for Chicago Fire 
> 2022-08-11 17:39:54 DEBUG :: SHOWQUEUE-SUBTITLE :: 258541: Downloading subtitles
> 2022-08-11 17:39:54 DEBUG :: SHOWQUEUE-SUBTITLE :: Checking subtitle candidates for Chicago Fire S05E04 (Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today.mkv)
> 2022-08-11 17:39:59 DEBUG :: SHOWQUEUE-SUBTITLE :: Unable to set <class 'subliminal.video.Episode'>.episode from episode.episode attribute
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956495278 is: 767/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362495 is: 773/48% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956498486 is: 361/22% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956223071 is: 766/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956223070 is: 765/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362445 is: 765/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1955362446 is: 766/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956500558 is: 768/47% (min=213/13%)
> 2022-08-11 17:40:12 DEBUG :: SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1956498481 is: 360/22% (min=213/13%)
> 2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: 258541: Downloaded English subtitles for Chicago Fire S05E04
> 2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: Parsed /home/stephenr/Videos/Chicago Fire/Chicago.Fire.S05E04.Nobody.Else.Is.Dying.Today into Chicago Fire - S05E04 [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
> 2022-08-11 17:40:14 DEBUG :: SHOWQUEUE-SUBTITLE :: formatting pattern: %SN - S%0SE%0E - %EN -> Chicago Fire - S05E04 - Nobody Else Is Dying Today
> ```
> 
> Add: I used the `Download Subtitles` button to trigger the search ![image](https://user-images.githubusercontent.com/10173496/184120611-ed114eb9-b6f3-42a9-a15b-1bc890e519eb.png)

I have only `Dutch` selected in the subtitles setting, when I get access to my pc ill try  to set it to English and test it again.

**Comment by miigotu** [comment] 2022-08-12 03:06
The language is irrelevant, and it is already fixed in master. It just has not been built and pushed to pypi (which is why all of the people having the problem are installed via pip)

**Comment by BKSteve** [comment] 2022-08-12 09:50
So for the `pip` installers what would be the best way to update?
Shutdown and edit `config.ini` 
`cur_commit_hash = d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5`
to previous update like this one which was 2 updates ago
`e943e010b959ffcc412ab098a332233ffd55350b`

Restart SC and then do an update to pull the latest tarball from GitHub?

**Comment by bradysvbc** [comment] 2022-08-12 18:12
> The language is irrelevant, and it is already fixed in master. It just has not been built and pushed to pypi (which is why all of the people having the problem are installed via pip)

That would explain it.. PIP install here.

**Comment by avdleeuw** [comment] 2022-08-13 12:37
> The language is irrelevant, and it is already fixed in master. It just has not been built and pushed to pypi (which is why all of the people having the problem are installed via pip)

I have this problem as well, and it doesn't seem to be solved by the mentioned fix. As far as I can see, the fix only seems to deal with the logging of the subtitle score? But as you can see from the logs in the previous replies, these subtitle scores are actually logged succesfully. So the error is generated at some later point in the code.

**Comment by miigotu** [comment] 2022-08-14 05:21
> So for the `pip` installers what would be the best way to update? Shutdown and edit `config.ini` `cur_commit_hash = d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5` to previous update like this one which was 2 updates ago `e943e010b959ffcc412ab098a332233ffd55350b`
> 
> Restart SC and then do an update to pull the latest tarball from GitHub?

You cannot update to a commit hash with a pip install.

I think this would do the trick:
```
pip uninstall sickchill
pip install git+https://github.com/sickchill/sickchill
```

**Comment by BKSteve** [comment] 2022-08-14 05:32
My mistake on the update mechanism inside SC then. 
So how would a pip install switch to develop or is that not possible?

**Comment by avdleeuw** [comment] 2022-08-14 11:57
I've created a pull-request that will get rid of the error message from the original issue.

**Comment by BKSteve** [comment] 2022-08-14 14:38
Per miigotu comment this is already fixed in `master`. If you happen to be on `pip install` then there's an updating conundrum. 
This will be resolved shortly (next `master` udpate)
In the meantime if you don't want to do the suggested uninstall and install then shutdown SC, ssh (or whatever) and curl the update file.
where ever your `subtitles.py` file is
`cd ~(your folder)/sickchill/oldbeard/subtitles.py`
`sudo curl -O https://github.com/SickChill/SickChill/blob/master/sickchill/oldbeard/subtitles.py`

This will pull that one file and you can restart.

**Comment by avdleeuw** [comment] 2022-08-14 14:44
Please see my comments in the pull request. This issue is **not** fixed by said commit.

**Comment by BKSteve** [comment] 2022-08-14 14:46
I saw your comment. The conundrum is with PIP installations.
The `master` has a fix in https://github.com/SickChill/SickChill/commit/167cad96a9ebe687f05b03c1b62fc8a2a991a795
Your pull request is identical.
The `pip` version on `pypi` is not properly updated. So you get the hash but not the code.

**Comment by avdleeuw** [comment] 2022-08-14 14:48
My pull request is NOT identical. My pull request fixes 'sickchill/show/History.py', while the other fix applies to 'sickchill/oldbeard/subtitles.py'

**Comment by avdleeuw** [comment] 2022-08-14 14:51
@BKSteve Anyway... if the fix was identical, I wouldn't even have been able to create the pull request in the first place...

**Comment by BKSteve** [comment] 2022-08-14 14:52
Apologies, code in subtitles and history is identical change.

```
                f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']})"
                f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores.res}/{scores.percent}% (min={scores.min}/{scores.min_percent})"
```

**Comment by avdleeuw** [comment] 2022-08-14 14:57
No problem, glad it's resolved :)

**Comment by miigotu** [comment] 2022-08-14 16:30
> My mistake on the update mechanism inside SC then. 
> So how would a pip install switch to develop or is that not possible?

It isn't really a recommended usage of pip to install from github directly ever. Almost always those users should install from the regular pip method (which pulls the wheel from pypi). People who know what they are doing that need to test something on develop, would normally be contributing back their findings to the team and be installing using a git clone (separate from their standard install)

However, it is entirely possible with:
```bash
pip uninstall sickchill
pip install git+https://github.com/sickchill/sickchill@develop
```

As this would taint their normal install and they should make a backup of their config and database and know how to uninstall and reinstall master before they ever try that.

**Closed** 2022-08-14 17:36 UTC
