### ISSUE TITLE
Newly added shows not scraping with Kodi

### ISSUE THREAD

**Issue by TheTruePhoenix** [SickChill/SickChill#5962] opened 2020-02-09 07:13 UTC
Branch/Commit: master/54a6134384b2dd4c442fea9bbc2b292dc3f5606e (v2020.02.05-2)
OS: Ubuntu 18.04
Browser: Chrome
What you did: Added new shows sometime this year
What happened: Kodi no longer scraps them correctly, if I delete the tvshow.nfo it works fine, it's like it's pointing to the wrong TVDB entries.
What you expected: Kodi to scrape them correctly.
Logs:
```
2020-02-09 04:44:31 INFO SHOWQUEUE-REFRESH :: Performing refresh on Schitt's Creek
~~~
2020-02-04 14:08:38 INFO SHOWQUEUE-ADD :: Copying from /share/Shows/Schitt's Creek/poster.jpg to /opt/sickchill/cache/images/287247.poster.jpg
2020-02-04 14:04:49 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /share/Shows/Schitt's Creek
```

As you can see it added fine, updates fine with-in SickChill but has broken Kodi.  That goes for every show I've added, at least from this year as far as I can tell.  I used Schitt's Creek as an example because it's an older show, but I only added it this year.

These were all shows I added from scratch with no existing episodes (Add New Show).   As a test I also deleted a show from SickChill, deleted the nfo and then tried an 'Add Existing Shows" and re-adding it from a search of existing files and got:

2020-02-09 07:00:25 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-02-09 07:00:17 INFO SHOWQUEUE-ADD :: 287247: Unable to find the show in the database
2020-02-09 07:00:10 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /share/Shows/Schitt's Creek

And EVENTUALLY (took ages) it was added as before.  Another scan on Kodi though and it still didn't pick it up :(  As per before if I deleted the nfo file it then could ID it no problem.

If I compare the way it's creating the nfo files now with how it did previously we get the following differences:

  <rating>8.6</rating>
^ community rating has now changed to it's MPAA rating?:
  <rating>TV-14</rating>

It's also got a line for mpaa, at the top just below <rating> instead of below <episodeguide>:
  <mpaa>TV-14</mpaa>

Other titles I can see also don't have <tvdbid> while all the new ones do.  I've changed and double checked that my settings for creating these files as the same as always.

Sorry if this is a repeat, I didn't see anything with this particular combo of issues listed.

Edit - Fixed a mistake above and also confirmed that changing the rating to a number and removing the mpaa didn't help.  The URL line is also a bit different.  I'm just going to past the entire things in a comment.

**Comment by TheTruePhoenix** [comment] 2020-02-09 07:21
An old nfo:
<?xml version='1.0' encoding='UTF-8'?>
<tvshow>
  <title>Star Trek: Discovery</title>
  <rating>8.1</rating>
  <year>2017</year>
  <plot>Set roughly ten years before the events of the original Star Trek, the series follows the crew of the USS Discovery as they discover new worlds and civilizations, while exploring the franchise's signature contemporary themes. The season-long story line revolves around an incident and an event in Star Trek history that's been talked about but never been explored.</plot>
  <episodeguide>
    <url>http://thetvdb.com/api/F9C450E78D99172E/series/328711/all/en.zip</url>
  </episodeguide>
  <mpaa>TV-MA</mpaa>
  <id>328711</id>
  <genre>Action</genre>
  <genre>Drama</genre>
  <genre>Adventure</genre>
  <genre>Science-Fiction</genre>
  <premiered>2017-09-24</premiered>
  <studio>CBS All Access</studio>
  <actor>
    <name>Sonequa Martin-Green</name>
    <role>Michael Burnham</role>
    <thumb>http://thetvdb.com/banners/actors/445688.jpg</thumb>
  </actor>
  <actor>
    <name>Ethan Peck</name>
    <role>Spock</role>
    <thumb>http://thetvdb.com/banners/actors/520483.jpg</thumb>
  </actor>
  <actor>
    <name>Anson Mount</name>
    <role>Christopher Pike</role>
    <thumb>http://thetvdb.com/banners/actors/520482.jpg</thumb>
  </actor>
  <actor>
    <name>Doug Jones</name>
    <role>Saru</role>
    <thumb>http://thetvdb.com/banners/actors/445689.jpg</thumb>
  </actor>
  <actor>
    <name>Jason Isaacs</name>
    <role>Gabriel Lorca</role>
    <thumb>http://thetvdb.com/banners/actors/445575.jpg</thumb>
  </actor>
  <actor>
    <name>Mary Wiseman</name>
    <role>Sylvia Tilly</role>
    <thumb>http://thetvdb.com/banners/actors/440156.jpg</thumb>
  </actor>
  <actor>
    <name>Anthony Rapp</name>
    <role>Paul Stamets</role>
    <thumb>http://thetvdb.com/banners/actors/440155.jpg</thumb>
  </actor>
  <actor>
    <name>Shazad Latif</name>
    <role>Ash Tyler</role>
    <thumb>http://thetvdb.com/banners/actors/440154.jpg</thumb>
  </actor>
  <actor>
    <name>Michelle Yeoh</name>
    <role>Philippa Georgiou</role>
    <thumb>http://thetvdb.com/banners/actors/467174.jpg</thumb>
  </actor>
  <actor>
    <name>Wilson Cruz</name>
    <role>Hugh Culber</role>
    <thumb>http://thetvdb.com/banners/actors/519212.jpg</thumb>
  </actor>
</tvshow>

**Comment by TheTruePhoenix** [comment] 2020-02-09 07:21
A new nfo:
<?xml version='1.0' encoding='UTF-8'?>
<tvshow>
  <title>Star Trek: Picard</title>
  <rating>TV-14</rating>
  <mpaa>TV-14</mpaa>
  <year>2020</year>
  <plot> Star Trek: Picard will take place after the destruction of the Romulan Empire and find Picard's life having been radically altered by the event.</plot>
  <episodeguide>
    <url>http://thetvdb.com/api/%(apikey)s/series/364093/all/en.zip</url>
  </episodeguide>
  <id>364093</id>
  <tvdbid>364093</tvdbid>
  <genre>Science Fiction</genre>
  <premiered>2020-01-09</premiered>
  <studio>CBS All Access</studio>
  <actor>
    <name>Patrick Stewart</name>
    <role>Jean-Luc Picard</role>
    <thumb>https://artworks.thetvdb.com/banners/actors/540295.jpg</thumb>
  </actor>
</tvshow>

**Comment by miigotu** [comment] 2020-02-09 19:50
The problem is the episodeguide, which is fixed in the last update
```xml
<episodeguide>
    <url>http://thetvdb.com/api/F9C450E78D99172E/series/328711/all/en.zip</url>
  </episodeguide>
```
should be now:
```xml
<episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;F9C450E78D99172E&amp;quot;,&amp;quot;id&amp;quot;:352016}|Content-Type=application/json</url>
  </episodeguide>
```

Without that fix kodi cannot scrape and only uses the data we give it.

There is no community ratings added to the nfo for kodi, that nfo is used for another player who uses the tag "rating" instead of "mpaa"

**Comment by miigotu** [comment] 2020-02-09 19:53
https://kodi.wiki/view/NFO_files/TV_shows#Template_nfo
https://forum.kodi.tv/showthread.php?tid=323588

**Closed** 2020-02-09 19:54 UTC

**Comment by miigotu** [comment] 2020-02-12 00:00
Ive made the rating change for you, to have the same behavior as before
