### ISSUE TITLE
Performance regression introduced in v2019.06.27-1

### ISSUE THREAD

**Issue by rob006** [SickChill/SickChill#5570] opened 2019-07-06 15:30 UTC
I'm using SickChill on Synology DS115j and recently I noticed constant CPU usage - there is always at least one thread that consuming ~30% of CPU.

![5db88aa5](https://user-images.githubusercontent.com/5972388/60758065-f7dfb700-a012-11e9-9ea2-ab3217e21bc9.png)

 I have no idea what it is doing. I enabled debug logs, but didn't find anything useful (regular tasks, like daily search, ends after few minutes at least, and they does not seem to be related to this one thread). I tried some older releases and the last version without this problem was [`v2019.05.31-1`](https://github.com/SickChill/SickChill/releases/tag/v2019.05.31-1). I'm not sure how useful it is - [v2019.05.31-1...v2019.06.27-1 diff](https://github.com/SickChill/SickChill/compare/v2019.05.31-1...v2019.06.27-1) is huge, but something went wrong with `v2019.06.27-1` release (30% CPU is quite a lot for such low power NAS, so recent version of SickChill is unusable on this device).

**Comment by basrieter** [comment] 2019-07-08 18:03
Same here on PC. 10% of the CPU!

**Comment by chuckchiam** [comment] 2019-07-11 04:24
same here.  windows 10, python.exe - running sickchill (as a service) consuming 8-15% of the cpu.  nothing interesting in the debug logs except for this during restart:

2019-07-10 18:01:45 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-07-10 18:01:45 DEBUG    MAIN :: Database upgrade required: Reset Version
2019-07-10 18:01:45 DEBUG    MAIN :: ResetDBVersion upgrade completed

**Comment by mike19715** [comment] 2019-07-11 22:23
I noticed the same thing.  Happening with the last 3 releases.  Went back to the 5-31 release with no issues.

**Comment by mike19715** [comment] 2019-07-18 15:42
Same here on win 10, about 10%, I rolled back to the 5-31 release.

**Comment by papaxris** [comment] 2019-07-24 13:30
I too can confirm this issue is a regression in Linux.

When updating to SickChill Release #5556 the following Issues were experienced:

- High CPU Utilization
- Wont Search for Custom HEVC

Rolled Back to Release #5263

**Comment by Christilut** [comment] 2019-07-27 08:47
Saw the same thing here.

Running ubuntu 16.04 with sickchill in docker. Consumes between 5% and 30% CPU at all times

**Comment by basrieter** [comment] 2019-08-10 13:30
Is there anyone that can pin point the exact commit that introduced this problem?

**Comment by andreofgyn** [comment] 2019-08-12 19:54
Yes, same thing with me, Windows 10 on a Liva and the constant 30-40% CPU Load, rolled back to commit #4d29e18 and it "fixed" the issue.

**Comment by basrieter** [comment] 2019-08-12 20:15
Does it already happens when starting it without any configuration?

**Comment by basrieter** [comment] 2019-08-12 21:15
The issue is cause by https://github.com/SickChill/SickChill/commit/289401cb23841f4eab09675670b5e2f489ac4c58 where the `autoreload` is enabled on line 90: https://github.com/SickChill/SickChill/blob/289401cb23841f4eab09675670b5e2f489ac4c58/sickbeard/webserveInit.py#L91 

This was moved to https://github.com/SickChill/SickChill/blob/master/sickchill/views/server_settings.py#L92

Disabling it seems to fix it?

**Comment by andreofgyn** [comment] 2019-08-13 19:23
Yes, disabling autoreload fixed the problem on the latest commit, thanks @basrieter.

**Comment by basrieter** [comment] 2019-08-13 21:34
That is good to hear. Hopefully my PR will be accepted then.

**Comment by WebSpider** [comment] 2019-08-14 09:47
Please test the develop branch, it has this fix embedded

**Comment by basrieter** [comment] 2019-08-14 09:47
Already checked it out and running it.

**Comment by MatejSpindler** [comment] 2019-08-29 15:03
I tried the develop branch and this problem is fixed. Ty.
Hopefully this gets merged to master soon.

**Comment by rob006** [comment] 2019-08-29 15:11
Same here - I've been using dev branch for about 4 days without any problem so far.

**Closed** 2019-09-02 11:15 UTC
