### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [5066fab] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by MotleyC** [SickChill/SickChill#4327] opened 2018-02-22 00:12 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5066fab] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by claytondukes** [comment] 2018-02-22 02:28
Installing nodejs seems to fix it (so far):
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by WebSpider** [comment] 2018-12-02 22:50
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:50 UTC
