### ISSUE TITLE
[APP SUBMITTED]: Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/318201/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43ce627a50>: Failed to establish a new connection: [Errno -2] Name or service not known',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318201/en.xml

### ISSUE THREAD

**Issue by ahummaida** [SickChill/SickChill#4925] opened 2018-08-24 08:38 UTC
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to connect to theTVDB while creating meta files - skipping - error Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/318201/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43ce627a50>: Failed to establish a new connection: [Errno -2] Name or service not known',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/318201/en.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-10-27 01:33
Duplicate of #4924

**Closed by WebSpider** 2018-10-27 01:33 UTC
