### ISSUE TITLE
SC Develop on Synology start failure

### ISSUE THREAD

**Issue by BKSteve** [SickChill/SickChill#7234] opened 2021-07-05 10:07 UTC
Error unable to restart SC on Synology DSM6 using Develop branch after switching from master to develop, restarting worked and updating then failed.

Develop: 926cf452ca95f35d1b2a87e2cd24776925acaba3 

```
Mon Jul  5 15:52:46 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/tv.py", line 33, in <module>
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/notifiers/__init__.py", line 3, in <module>
    from sickchill.oldbeard.notifiers import (  # twilio_notify,
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/notifiers/kodi.py", line 4, in <module>
    from beekeeper.exceptions import RequestTimeout
ModuleNotFoundError: No module named 'beekeeper'
```

**Comment by andress134** [comment] 2021-07-05 13:16
> beekeeper
i see here say  ModuleNotFoundError: No module named 'beekeeper'

pip3 install beekeeper

**Comment by BKSteve** [comment] 2021-07-05 13:33
This is a Synology DSM so a little trickier. Any suggestions on where to execute this install to ensure it ends up in correct location?
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages folder

**Comment by andress134** [comment] 2021-07-05 13:40
pip3.7 install beekeeper -U

**Comment by BKSteve** [comment] 2021-07-05 14:02
I wish it were so simple. pip3 is here
/var/packages/python3/target/bin/pip3
then I need to make sure it installs beekeeper here
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages/

So I was looking in the code so I can duplicate a similar string and get it in the right place with the right permissions.

**Comment by BKSteve** [comment] 2021-07-05 14:58
Easier than I thought.

I just copied the files from the develop branch to my DSM, these two had to be copied in.

- beekeeper
- kodipydent

**Comment by miigotu** [comment] 2021-07-06 05:27
copying stuff into site packages is a big no-no. pip/poetry manages the files in that directory.
` /volume1/@appstore/sickchill/env/bin/pip install -U poetry` would install poetry, and the n you just start SC and it will install its own dependencies..

**Comment by BKSteve** [comment] 2021-07-06 14:02
Thanks, went to folder /volume1/@appstore/sickchill/env/lib/python3.7/site-packages and did the pip install.
Which loaded many more items, here's the list. (did this after I updated with: Try to fix #7234)
```
cachy
cachy-0.3.0.dist-info
cleo
cleo-0.8.1.dist-info
clikit
clikit-0.6.2.dist-info
crashtest
crashtest-0.3.1.dist-info
distlib
distlib-0.3.2.dist-info
importlib_metadata
importlib_metadata-1.7.0.dist-info
jeepney
jeepney-0.6.0.dist-info
keyring
keyring-21.8.0.dist-info
lockfile
lockfile-0.12.2.dist-info
pastel
pastel-0.2.1.dist-info
pexpect
pexpect-4.8.0.dist-info
pkginfo
pkginfo-1.7.0.dist-info
poetry
poetry-1.1.7.dist-info
poetry_core-1.0.3.dist-info
ptyprocess
ptyprocess-0.7.0.dist-info
pylev
pylev-1.4.0.dist-info
secretstorage
SecretStorage-3.3.1.dist-info
shellingham
shellingham-1.4.0.dist-info
tomlkit
tomlkit-0.7.2.dist-info
urllib3
urllib3-1.25.11.dist-info
virtualenv
virtualenv-20.4.7.dist-info
wheel
```

**Comment by BKSteve** [comment] 2021-07-06 14:29
I was looking at the  sickchill/init_helpers.py and wondering where the log gets stored? 
Or does it only get stored if SC fails to start?
Wanted to see whether the pip function did it's job.

**Comment by miigotu** [comment] 2021-07-06 21:05
You shouldn't have to manually install anything... After my fixes you should have been able to just got pull and start it. Can't log from init_helpers, it's just printed to the console.

**Comment by BKSteve** [comment] 2021-07-07 06:48
OK, removed. Reinstalled, restored master backup, switched to develop and restarted.
Same Beekeeper issue missing.
```
Wed Jul  7 11:02:34 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
>>> as above
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/notifiers/kodi.py", line 4, in <module>
    from beekeeper.exceptions import RequestTimeout
ModuleNotFoundError: No module named 'beekeeper'
```

after pip poetry and restart SC still not loading of Beekeeper.
```
Wed Jul  7 12:07:59 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
ERROR: Invalid requirement: ''
ERROR: Invalid requirement: ''
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
>>> as above
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/notifiers/kodi.py", line 4, in <module>
    from beekeeper.exceptions import RequestTimeout
ModuleNotFoundError: No module named 'beekeeper'
```
Open to suggestions on how to help track this down and resolve.

**Comment by BKSteve** [comment] 2021-07-07 08:13
pip install results for 2 items.
beekeeper 
```
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages# /volume1/@appstore/sickchill/env/bin/pip install -U beekeeper
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
Requirement already up-to-date: beekeeper in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages (0.9.2)
Requirement already satisfied, skipping upgrade: xmltodict<=0.10.1,>=0.9.2 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages (from beekeeper) (0.10.1)
WARNING: You are using pip version 20.0.2; however, version 21.1.3 is available.
You should consider upgrading via the '/volume1/@appstore/sickchill/env/bin/python -m pip install --upgrade pip' command.
```

kodipydent
```
/volume1/@appstore/sickchill/env/bin/pip install -U kodipydent
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
Collecting kodipydent
  WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
  Downloading kodipydent-0.3.1-py2.py3-none-any.whl (5.9 kB)
Requirement already satisfied, skipping upgrade: beekeeper==0.9.2 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages (from kodipydent) (0.9.2)
Requirement already satisfied, skipping upgrade: xmltodict<=0.10.1,>=0.9.2 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages (from beekeeper==0.9.2->kodipydent) (0.10.1)
Installing collected packages: kodipydent
Successfully installed kodipydent-0.3.1```

Both are successfully installed and SC can start.

**Comment by miigotu** [comment] 2021-07-07 08:37
Finally figured it out =P

**Comment by miigotu** [comment] 2021-07-07 08:39
The key is the `ERROR: Invalid requirement: ''`... SC is not started from the SC directory on synology, so poetry never found the pyproject.toml. fixed in my synotest branch (and tested on a synology)

**Comment by BKSteve** [comment] 2021-07-07 08:52
As you have a syno box to test it on I'll wait for the push to develop.

**Comment by miigotu** [comment] 2021-07-07 08:52
A git pull fixes it permanently, you could back up your SC, reinstall the SC package, and restore to check (and clean up all you did manually)

**Closed by miigotu** 2021-07-07 08:52 UTC

**Comment by BKSteve** [comment] 2021-07-07 09:04
Just did a full SC reinstall, restore. No beekeeper still.

**Comment by BKSteve** [comment] 2021-07-07 09:30
pip poetry restart gives

```
Wed Jul  7 16:27:05 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
ERROR: Will not install to the user site because it will lack sys.path precedence to cleo in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to virtualenv in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to certifi in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to certifi in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
Traceback (most recent call last):
>>> as above
ModuleNotFoundError: No module named 'beekeeper'
```

**Comment by miigotu** [comment] 2021-07-07 09:55
Make sure you actually did a git pull on develop AFTER I merged it from synotest to develop. I tested this here locally on my syono vm

**Comment by BKSteve** [comment] 2021-07-07 10:01
I can't find specifically where to do a git pull, every where I try I always get error messages.
My restore was already develop, maybe I'll do a fresh install, switch to develop, restart then restore.

**Comment by BKSteve** [comment] 2021-07-07 10:19
Reinstall, restore, restart, working (no poetry in folder so must still be master), one update. Cannot start.
```
Wed Jul  7 17:14:45 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /volume1/@appstore/sickchill/env/lib/python3.7/site-packages
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
ERROR: Invalid requirement: '/bin/sh: poetry: command not found'
Hint: It looks like a path. File '/bin/sh: poetry: command not found' does not exist.
/volume1/@appstore/sickchill/env/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
```

**Comment by miigotu** [comment] 2021-07-08 02:29
I'll make it more robust, but I'm already doing it exactly how other projects do it (poetry, pip, etc)

Before you do a git pull/checkout/etc:

```bash
sudo -u sc-sickchill /bin/bash
# edit .git/config and change the /refs/heads/master to /refs/heads/* I think, only the last section should have master in it
git fetch --unshallow 
git checkout develop
```

**Comment by BKSteve** [comment] 2021-07-08 13:24
The issue is I can't do a git pull.  There is no .git directory anywhere in the sickchill folders on the DSM.

Git pull as sudo gives:  
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by BKSteve** [comment] 2021-07-08 15:52
Mucked around a lot, did some stupid stuff.
Removed and reinstalled.
Restored, restarted, restarted. 
poetry, beekeeper, kodipydent all loaded in  /volume1/@appstore/sickchill/env/lib/python3.7/site-packages

FYI, these aren't listed in wheelhouse folder. /volume1/@appstore/sickchill/share/wheelhouse

**Comment by BKSteve** [comment] 2021-07-08 16:02
Spoke too soon. 
Switched back to master, restart, which cleared out the files, 
Switched back to develop, 68 updates, crashed. beekeeper error.

**Comment by miigotu** [comment] 2021-07-08 23:49
There is a .git dir on syno, unless you are using someone elses package.
The wheels do not matter, what is the arch of your syno?

```bash
cd /var/packages/sickchill/target/share/SickChill
sudo -u sc-sickchill /bin/bash
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch --unshallow 
git checkout develop
```

This is the way, with nyaran's package on synocommunity.
```bash
⚡️33% ❯ ssh 192.168.10.21
miigotu@192.168.10.21's password: 
miigotu@DiskStation:/$ cd /var/packages/sickchill/target/share/SickChill/
miigotu@DiskStation:/var/packages/sickchill/target/share/SickChill$ ls -dl .git
drwxr-xr-x 8 sc-sickchill sickchill 4096 Jul  7 04:19 .git
miigotu@DiskStation:/var/packages/sickchill/target/share/SickChill$ sudo -u sc-sickchill /bin/bash
Password: 
bash-4.3$ git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
bash-4.3$ git fetch --unshallow
bash-4.3$ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
bash-4.3$ git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (7/7), 1.33 KiB | 136.00 KiB/s, done.
From https://github.com/SickChill/SickChill
   e47c49434..f92f6e5e4  develop    -> origin/develop
Updating e47c49434..f92f6e5e4
Fast-forward
 .github/workflows/pythonpackage.yml | 32 +++++++++++++++++++++++---------
 sickchill/init_helpers.py           | 33 ++++++++++++++++++++++-----------
 2 files changed, 45 insertions(+), 20 deletions(-)
```

**Comment by miigotu** [comment] 2021-07-08 23:56
Whats the output of `uname -a` on your syno?

**Comment by BKSteve** [comment] 2021-07-09 04:46
`uname -a` gives:
`Linux SRStation 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:35 CST 2021 x86_64 GNU/Linux synology_apollolake_1019+`

I have installed nyaran's package from synocommunity.
root@SRStation:/# cd /var/packages/sickchill/target/share/SickChill/
root@SRStation:/var/packages/sickchill/target/share/SickChill# ls -dl .git
**`ls: cannot access .git: No such file or directory`**


bash-4.3$ ls -dl .git
ls: cannot access .git: No such file or directory
so there is no .git folder  - and this is the weird part.

folder contains directories
`.github, contrib, lib3, sickchill, tests`
files
`.appveyor.yml, .bettercodehub.yml, .bowerrc, .checkignore, .codecov.yml, .dockerignore, .editorconfig, .gitattributes, .gitignore, .lgtm.yml, .snyk, .travis.yml, bower.json, CONTRIBUTORS.md, COPYING.txt, crowdin.yaml, docker-compose.yaml, Dockerfile, Gruntfile.js, LICENSE.md, package.json, poetry.lock, poetry.toml, pyproject.toml, README.md, requirements.txt, SECURITY.md, setup.cfg, setup.py, SickChill.py, yarn.lock, `

It's like the .git folder gets removed somewhere in the process.
Is there a way to recreate the .git folder and link?

**Comment by miigotu** [comment] 2021-07-09 06:18
Did you start the package first before checking for the git folder? I'm working with the same package on x86_64. The problem is happening because the venv created includes site packages, and your main python has an incompatible version of urllib3 so we can't install that in the venv (shadowing is not allowed)

I'm working on a way to figure out how to disable site packages in the venv at runtime, or recreate it maybe. This is crazy. You should have a git folder once you start it once at least because the package is supposed to pull from git. You sure you aren't installing his older package?

**Comment by BKSteve** [comment] 2021-07-09 06:23
I'm using the one directly in the Synocommunity repository through the package center.
![image](https://user-images.githubusercontent.com/10173496/125032922-d9f13500-e0b8-11eb-8a16-09f3867f929a.png)

**Comment by miigotu** [comment] 2021-07-09 06:36
Could you try stopping SC, and edit `/var/packages/sickchill/target/env/pyvenv.cfg` change 
```diff
--- include-system-site-packages = true
+++ include-system-site-packages = false
```

**Comment by BKSteve** [comment] 2021-07-09 06:43
Experiment:
Uninstalled - all gone no sichchill in @appstore folder aka /var/packages
Reinstall - run after installation unticked. - no .git in /var/packages/sickchill/target/share/SickChill
Run - 689 commits behind, still not .git folder.
Update - still no .git folder.

interupt experiment for +++ include-system-site-packages = false

**Comment by BKSteve** [comment] 2021-07-09 07:08
Went back to the beginning.
New install. edit pyvenv.cfg saved and started SC. 
Updated no .git folder. Restored my backup, no .git folder

**Comment by BKSteve** [comment] 2021-07-09 07:19
If it's a pip install does it get a .git folder?

https://github.com/SynoCommunity/spksrc/blob/master/spk/sickchill/src/service-setup.sh
```
 ${PIP} install --no-deps --no-index -U --force-reinstall -f ${SYNOPKG_PKGDEST}/share/wheelhouse ${SYNOPKG_PKGDEST}/share/wheelhouse/*.whl >> ${INST_LOG} 2>&1
```

**Comment by miigotu** [comment] 2021-07-09 07:22
@BKSteve That is just installing dependencies (the wheels) in the venv (which is unnecesary, the package needs updated), SC is not installed via pip there.

I think my last 2 commits might fix it, I was able to reproduce the error, but I did have to change permissions on the venv (ill test some more)

5e712a37cf27740d6c68b9b983ef5497c0e73317
6d14702eeb1ab1bca70a39502f4f51595fba9d5d

**Comment by miigotu** [comment] 2021-07-09 08:00
Ugh:
```bash
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/volume1/@appstore/sickchill/env/bin/easy_install'
Consider using the `--user` option or check the permissions.

ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

```

**Comment by miigotu** [comment] 2021-07-09 08:07
Now, if you 
```bash
sudo chmod -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env
```
and start develop it will run... the venv is not created correctly, it should not have system site packages and it should have permissions of the process using it...

**Comment by BKSteve** [comment] 2021-07-09 08:23
OK, `chown `ed the folder. 
First start pulled in poetry, but failed. Second start pulled in beekeeper and others.
Running

**Comment by BKSteve** [comment] 2021-07-09 08:28
How much fun will it be to move to DSM7??

**Comment by miigotu** [comment] 2021-07-09 10:26
I think it will be fine, if they just let me make the package properly smh

**Comment by BKSteve** [comment] 2021-07-09 17:01
Anyway DSM7 can wait. BV and PA look to be have a heavy conversation on the matter.
