### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [5aad224] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by oookamiii** [SickChill/SickChill#5694] opened 2019-11-17 08:49 UTC
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-0.bpo.6-amd64-x86_64-with**
Locale: None
Branch: **develop**
Commit: SickChill/SickChill@5aad224493c6eacbbc6b59793a55994915331032
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5aad224] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment] 2019-11-18 14:02
Duplicate of #5688

**Closed** 2019-11-19 13:57 UTC

**Comment by MichelRabozee** [comment] 2019-11-19 17:35
#5688 was about AppleTV+
This one is about Disney+ missing in the time zones data...
