### ISSUE TITLE
Error on Search Providers Page

### ISSUE THREAD

**Issue by jj5000** [SickChill/SickChill#4703] opened 2018-05-15 22:51 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
Browser: Chrome
What you did: Opened the Search Providers Page
What happened: Mako Error
What you expected: To see the list of providers and make changes
Logs:
```
File C:/SickRage/gui/slick/views/config_providers.mako:183, in render_pages:
${('', 'checked="checked"')[curNewznabProvider.enable_daily]}

TypeError: tuple indices must be integers, not unicode
```

**Comment by ravensorb** [comment] 2018-05-16 22:45
Getting the same issue after updated to the latest build

**Comment by jj5000** [comment] 2018-05-31 02:52
Rolled back to 39c5dc6 and it works so it is one of the recent changes that has caused the issue

**Comment by ravensorb** [comment] 2018-07-19 01:42
is this a duplicate of #4721

**Comment by jj5000** [comment] 2018-07-19 02:12
Yes.  Can confirm the fix from @SudoHenk from #4721 works

**Closed** 2018-10-30 14:28 UTC
Labels: Old - Tag to reopen
