### ISSUE TITLE
[APP SUBMITTED]: Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/311945/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15166a5f7790>: Failed to establish a new connection: [Errno -3] Try again',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/311945/en.xml

### ISSUE THREAD

**Issue by blade316** [SickChill/SickChill#5678] opened 2019-11-07 02:11 UTC
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/311945/en.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15166a5f7790>: Failed to establish a new connection: [Errno -3] Try again',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/311945/en.xml
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment] 2019-11-18 11:16
TheTVDB has multiple issues at the moment, please see #5608 
Closing this as duplicate of #5686

**Closed by WebSpider** 2019-11-18 11:16 UTC
