### ISSUE TITLE
Synology Docker 8081 port occupied. 

### ISSUE THREAD

**Issue by danuwaanalihi** [SickChill/SickChill#6977] opened 2021-01-21 22:49 UTC
I am struggling with Docker install of sickchill on synology. I have installed other containers like radarr, plex or pihole so I am not total newbie. 
I am using linuxserver container and I have followed instructions to the dot. However when I try to setup port number it says that port is already occupied by other service so I tried to put other ports in settings for both container and remote ports. I still can't get to  get it running. 
This is fresh log after start. I have set port to 7632 (container and local).  I have tried as well to keep local at 8081 and change external one only. It didn't work. Please advise!
LOG:

date | stream | content
-- | -- | --
2021-01-21 22:43:30 | stdout | 2021-01-21 23:43:26 INFO :: CHECKVERSION :: Checking for updates using PIP
2021-01-21 22:43:30 | stdout | 2021-01-21 23:43:26 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2021-01-21 22:43:30 | stdout | 2021-01-21 23:43:26 INFO :: MAIN :: Starting SickChill [pip] using '/config/config.ini'
2021-01-21 22:43:16 | stdout | /usr/lib/python3.8/site-packages/sickchill/locale
2021-01-21 22:43:04 | stdout | /usr/lib/python3.8/site-packages/sickchill/locale
2021-01-21 22:41:48 | stdout | /usr/lib/python3.8/site-packages/sickchill/locale
2021-01-21 22:41:47 | stdout | /usr/lib/python3.8/site-packages/sickchill/locale
2021-01-21 22:40:45 | stdout | [services.d] done.
2021-01-21 22:40:45 | stdout | [services.d] starting services
2021-01-21 22:40:45 | stdout | [cont-init.d] done.
2021-01-21 22:40:45 | stdout | [cont-init.d] 99-custom-files: exited 0.
2021-01-21 22:40:45 | stdout | [custom-init] no custom files found exiting...
2021-01-21 22:40:45 | stdout | [cont-init.d] 99-custom-files: executing...
2021-01-21 22:40:45 | stdout | [cont-init.d] 30-config: exited 0.
2021-01-21 22:40:45 | stdout | Setting permissions
2021-01-21 22:40:45 | stdout | ln: failed to create symbolic link '/app/sickchill/sickchill': File exists
2021-01-21 22:40:41 | stdout | [cont-init.d] 30-config: executing...
2021-01-21 22:40:41 | stdout | [cont-init.d] 10-adduser: exited 0.
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout | -------------------------------------
2021-01-21 22:40:41 | stdout | User gid:    101
2021-01-21 22:40:41 | stdout | User uid:    1026
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout | -------------------------------------
2021-01-21 22:40:41 | stdout | GID/UID
2021-01-21 22:40:41 | stdout | -------------------------------------
2021-01-21 22:40:41 | stdout | https://www.linuxserver.io/donate/
2021-01-21 22:40:41 | stdout | To support LSIO projects visit:
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout | SickChill: https://www.patreon.com/SickChill
2021-01-21 22:40:41 | stdout | To support the app dev(s) visit:
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout | -------------------------------------
2021-01-21 22:40:41 | stdout | Brought to you by linuxserver.io
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:41 | stdout | \|_\| \|___/ \|_\|  \__/
2021-01-21 22:40:41 | stdout | \| \| \__ \ \| \| \| () \|
2021-01-21 22:40:41 | stdout | \| \| / __\| \| \|  /  \
2021-01-21 22:40:41 | stdout | \| \|  ___   _    __
2021-01-21 22:40:41 | stdout | _         ()
2021-01-21 22:40:41 | stdout | -------------------------------------
2021-01-21 22:40:41 | stdout |  
2021-01-21 22:40:39 | stdout | usermod: no changes
2021-01-21 22:40:37 | stdout | [cont-init.d] 10-adduser: executing...
2021-01-21 22:40:37 | stdout | [cont-init.d] 01-envfile: exited 0.
2021-01-21 22:40:37 | stdout | [cont-init.d] 01-envfile: executing...
2021-01-21 22:40:37 | stdout | [cont-init.d] executing container initialization scripts...
2021-01-21 22:40:37 | stdout | [fix-attrs.d] done.
2021-01-21 22:40:37 | stdout | [fix-attrs.d] applying ownership & permissions fixes...
2021-01-21 22:40:35 | stdout | [s6-init] ensuring user provided files have correct perms...exited 0.
2021-01-21 22:40:32 | stdout | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.

**Comment by miigotu** [comment] 2021-01-22 00:21
Remove sickbeard-custom

**Comment by danuwaanalihi** [comment] 2021-01-22 09:28
> Remove sickbeard-custom

thanks a lot for your response!. however - I am thinking about migrating to dsm7 in case i would succeed to move all packages I need to docker. Therefore I wouldn't like to risk removing it if I can't make it run. sickbeard-custom runs on other port anyway and should not be blocked by it. Is it possible to set custom ports so I can make it run without removing sickbeard-custom version?

**Comment by danuwaanalihi** [comment] 2021-01-22 10:14
> Remove sickbeard-custom

ok. I took the leap of faith and backed up sickbeard custom. port has been changed now. I have restored backup and need to configure torrents and download client but in general it seems to be working. thx

**Comment by 0ddb0d** [comment] 2021-01-30 03:17
Since the problem is resolved please close this issue.

**Closed** 2021-01-31 14:21 UTC
