### ISSUE TITLE
pip update from sickchill ui is broken

### ISSUE THREAD

**Issue by pigsyn** [SickChill/sickchill#8178] opened 2022-09-17 11:03 UTC
# Notice: Updating to 2022.9.22 will still require manual update. Updater is fixed in 2022.9.22 and will not need manually done from here on out.

Version: 2022.9.14 and above
OS: Ubuntu pip | Windows pip
Browser: chrome
What you did: update to newest version from the UI (There is a newer version available — Update Now)
What happened: UI error : Update Failed Update wasn't successful, not restarting. Check your log for more information.
What you expected: Update to 2022.9.17
Logs:
```
2022-09-17 11:29:57 INFO :: WEBSERVER-HOME_0 :: Command result: ERROR: Could not find a version that satisfies the requirement s (from versions: none)
2022-09-17 11:29:57 INFO :: WEBSERVER-HOME_0 :: Trying user site-packages
AA ERROR: No matching distribution found for s
2022-09-17 11:29:57 INFO :: WEBSERVER-HOME_0 :: Command result: ERROR: Could not find a version that satisfies the requirement s (from versions: none)
2022-09-17 11:29:56 DEBUG :: WEBSERVER-HOME_0 :: pip args: ['/usr/bin/python3', '-m', 'pip', 'install', '--no-input', '--disable-pip-version-check', '--no-python-version-warning', '--no-color', '-qU', '--find-links=https://wheel-index.linuxserver.io/ubuntu/', 's', 'i', 'c', 'k', 'c', 'h', 'i', 'l', 'l']
2022-09-17 11:28:53 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
```

Needs either a list for pip_install(["sickchill"]) and cmd.extend(packages) 
or a string and cmd.append(packages)
https://github.com/SickChill/SickChill/blob/583063e18c3638a75f1bc85994610a63fdf3bbf1/sickchill/update_manager/pip.py#L72-L74
https://github.com/SickChill/SickChill/blob/583063e18c3638a75f1bc85994610a63fdf3bbf1/sickchill/update_manager/pip.py#L135

### linux
Update is working from pip cli on linux, using pip migration guide:
```
sudo systemctl stop sickchill
sudo su - sickchill -s /bin/bash
pip install -U sickchill
exit
sudo systemctl restart sickchill
```

### Windows
Quickest fix in my opinion for windows users is to uninstall SickChill with windows Programs and Features, answer **NO** when asked to remove SickChill database and configuration, then reinstall with SickChillInstaller, you will get the latest version
Do a backup first

### macOS
```
launchctl unload ~/Library/LaunchAgents/SickChill.plist
pip3 install -U sickchill
launchctl load ~/Library/LaunchAgents/SickChill.plist
```

**Comment by ronrosenfeld** [comment] 2022-09-17 15:50
Will the windows installer also install a version of Python?  Or does that need to be done separately (I have multiple versions of Python in my windows system)

**Comment by miigotu** [comment] 2022-09-17 16:54
> @pigsyn  Will the windows installer also install a version of Python?  Or does that need to be done separately (I have multiple versions of Python in my windows system)

It does, but if you have your own python you could install it yourself in that environment and add your own service to run it.

**Comment by pigsyn** [comment] 2022-09-17 16:54
@ronrosenfeld It currently installs a version (3.8.10) in `C:\SickChill\Python3` wich is used by nssm and SickChill.
Doesn't interfere with a system wide python3.10 install for me

**Comment by miigotu** [comment] 2022-09-17 17:00
`C:\SickChill\Python3\tools\python.exe -m pip install -U sickchill ` is the command to update SickChill for users of the windows installer currently.

I feel like install/update guides can mostly be consolidated into one wiki page.

**Comment by ronrosenfeld** [comment] 2022-09-17 17:10
@miigotu  Thank you for that.  It worked and SC can now again find episodes.

FWIW, I stopped SC before and restarted after.  So my entire code sequence was:

```
C:\>net stop sickchill
C:\>C:\SickChill\Python3\tools\python.exe -m pip install -U sickchill
C:\>net start sickchill
```

**Comment by miigotu** [comment] 2022-09-17 17:31
> @miigotu  Thank you for that.  It worked and SC can now again find episodes.
> 
> And, with that correct code, it was simple and fast.
> 
> FWIW, I stopped SC before and restarted after.  So my entire code sequence was:
> 
> ```
> C:\>net stop sickchill
> C:\>C:\SickChill\Python3\tools\python.exe -m pip install -U sickchill
> C:\>net start sickchill
> ```
> I truly appreciate all the work that you have been putting in for this.
> 
> Any idea as to what will happen with docker support?  (I have another machine where SC is running on a Synology box under docker.
> 

Docker uses a pip install, so it's exactly the same. Ideally though, you should use watchtowerr to auto update the container when new ones are built rather than updating inside the container. That was part of the decision to force everything to use the same install method. It is the standard practice, all systems use the same install method now and the guides and wikis can be simplified. All platforms will have the same commands, likely just a different directory and maybe activation of a virtualenv. It makes it the same everywhere.

**Comment by ronrosenfeld** [comment] 2022-09-17 17:47
`Docker uses a pip install, so it's exactly the same. Ideally though, you should use watchtowerr to auto update the container when new ones are built rather than updating inside the container. `

The watchtower command line I have (from you, some time ago) to use on my synology:
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once sickchill
```
In a few weeks when I'm at that location, I'll give it a try and report back.

**Comment by miigotu** [comment] 2022-09-17 21:53
#8182 fixes the pip update so it wont be broken on next release (once you get the next release manually with a pip update or docker update)

**Comment by DrDrewZA** [comment] 2022-09-18 10:16
I tried all sorts of things to get my install to update - been unable to update on windows for the last couple of updates, but just been waiting for the auto-download fix to move from develop to master.  now that it did, I could not, no matter what I tried from the command line or in the interface, get it to update.

Until I tried the below from @pigsyn that is.  Worked like a charm and all is well with my install - many thanks.
 
> ### Windows
> Quickest fix in my opinion for windows users is to uninstall SickChill with windows Programs and Features, answer **NO** when asked to remove SickChill database and configuration, then reinstall with SickChillInstaller, you will get the latest version Do a backup first

**Comment by miigotu** [comment] 2022-09-18 19:22
https://github.com/SickChill/SickChill/wiki/Pip is a good one also, it's still being worked on.

I'd rather have a big wiki page like this with basic instructions for many platforms, with a link to another page for each platform for more specific instructions. 

Installation, Backup, Updating, and config settings are all we really need. The old wiki needs cleared out of stuff that doesn't work or isn't supported.

Does anyone have experience with debhelper?

**Comment by miigotu** [comment] 2022-09-22 08:49
# Notice: Updating to 2022.9.22 will still require manual update. Updater is fixed in 2022.9.22 and will not need manually done from here on out.

**Comment by wallacebrf** [comment] 2022-09-23 18:27
just checking, i have updated to 9.22.2022 yesterday in docker on synology. 
update appears to have gone well but i am getting this notification at the top of the page

`SickChill no longer is supported unless installed with pip or poetry. Source and git installs are for experienced users only`

i used portainer to get to Sickchill's terminal and performed the `pip install -U sickchill`  command and it did perform some updates, but the banner is still showing. 

i am mostly just confirming if i just need to perform the `pip install -U sickchill` command again after the next update or if i am just fine as i am. when i perform the "check for updates" through the GUI, the logs show that updates through GIT is not supported as the banner indicated 

here are my details

```
SickChill Info:
Install: pip
Version: 2022.9.22
Database Version: 44.2

  Python Version:3.9.8 (main, Nov 10 2021, 03:02:59) [GCC 10.2.1 20210110]

  SSL Version:OpenSSL 1.1.1k 25 Mar 2021

  OS:Linux-4.4.180+-x86_64-with-glibc2.31

  Locale:en_US.UTF-8
```

**Comment by miigotu** [comment] 2022-09-23 19:00
> just checking, i have updated to 9.22.2022 yesterday in docker on synology. 
> update appears to have gone well but i am getting this notification at the top of the page
> 
> `SickChill no longer is supported unless installed with pip or poetry. Source and git installs are for experienced users only`
> 
> i used portainer to get to Sickchill's terminal and performed the `pip install -U sickchill`  command and it did perform some updates, but the banner is still showing. 
> 
> i am mostly just confirming if i just need to perform the `pip install -U sickchill` command again after the next update or if i am just fine as i am. when i perform the "check for updates" through the GUI, the logs show that updates through GIT is not supported as the banner indicated 
> 
> here are my details
> 
> ```
> SickChill Info:
> Install: pip
> Version: 2022.9.22
> Database Version: 44.2
> 
>   Python Version:3.9.8 (main, Nov 10 2021, 03:02:59) [GCC 10.2.1 20210110]
> 
>   SSL Version:OpenSSL 1.1.1k 25 Mar 2021
> 
>   OS:Linux-4.4.180+-x86_64-with-glibc2.31
> 
>   Locale:en_US.UTF-8
> ```

If you have that notification, you aren't starting it correctly (not running the correct install, more than one install) or are not actually installed with pip.

**Comment by miigotu** [comment] 2022-09-23 19:07
I overlooked the docker file, I thought it was using a pip install but it is started wrong. I'll fix the cmd line in the docker files later.

**Comment by miigotu** [comment] 2022-09-23 21:08
@wallacebrf let's see how this builds, trying to add back arm builds to it also: d8c180a832e72e77791036fcbbca40764ff5c28a

**Comment by miigotu** [comment] 2022-09-24 00:32
So I got the docker file built properly on develop , you can pull it as sickchill/sickchill:edge or sickchill/sickchill: develop

Side note: I also got it building properly for arm/v6 and arm/v7, going to add arm/v8 and maybe risc and Solaris and an alpine version later.

Then, I'll copy out the wheels it builds to an artifact, so people can use those wheels in their regular installs 😂 it's going to be good.

**Comment by wallacebrf** [comment] 2022-09-25 21:36
> So I got the docker file built properly on develop , you can pull it as sickchill/sickchill:edge or sickchill/sickchill: develop
> 
> Side note: I also got it building properly for arm/v6 and arm/v7, going to add arm/v8 and maybe risc and Solaris and an alpine version later.
> 
> Then, I'll copy out the wheels it builds to an artifact, so people can use those wheels in their regular installs 😂 it's going to be good.

i will be trying the sickchill/sickchill: develop

just want to confirm if i should move to the "develop," version and stay there, or if i should stay on master (which i currently am on) and wait for the next update to the master that fixes the banner issue?

**Comment by miigotu** [comment] 2022-09-25 21:47
> > So I got the docker file built properly on develop , you can pull it as sickchill/sickchill:edge or sickchill/sickchill: develop
> > Side note: I also got it building properly for arm/v6 and arm/v7, going to add arm/v8 and maybe risc and Solaris and an alpine version later.
> > Then, I'll copy out the wheels it builds to an artifact, so people can use those wheels in their regular installs joy it's going to be good.
> 
> i will be trying the sickchill/sickchill: develop
> 
> just want to confirm if i should move to the "develop," version and stay there, or if i should stay on master (which i currently am on) and wait for the next update to the master that fixes the banner issue?

With docker it doesn't matter. You can freely switch back and forth between tags and not lose any data. Use what works, then when mater is fixed switch back to master (so you dont get a broken develop version someday)

**Comment by ebaydan777** [comment] 2022-09-26 05:31
so @miigotu does sickchill via Docker no longer work? I am a bit confused..

**Comment by miigotu** [comment] 2022-09-26 10:22
> 

It does, there is just an issue with building newer images, and building arm images. I can remove arm from the mix and it will build fine, but I'm trying to get them to build correctly. Any image you get from dockerhub will work, they just have the notice about git installs because they call the wrong script. Should be fixed now thoug in develop, hopefully. I just spent 3+ days with @pigsyn fixing it.

**Comment by ronrosenfeld** [comment] 2022-10-03 22:52
@miigotu Not sure if this is expected behavior at this time.  But here, docker install works only with `develop` branch.

```
OS:  Synology: Docker
docker pull sickchill/sickchill => latest and does not run (runs briefly, then stops and tries to restart over and over again)
docker pull sickchill/sickchill:develop => a running container
      Install: pip
      Version: 2022.9.28
```

**Comment by miigotu** [comment] 2022-10-03 23:15
Yes, we know docker master/lastest is not currently working. It will soon.

**Comment by miigotu** [comment] 2022-10-08 09:01
docker master/latest fixed as soon as master builds

**Closed by miigotu** 2022-10-08 09:01 UTC

**Comment by twinden** [comment] 2022-10-09 20:21
I tried all this on my Synology.
( python3 -m pip install -U sickchill )

Installation ends with error : failed building wheel for pynacl / Failed to build cryptography pynacl
Could not build wheels for cryptography, pynacl, which is required to install pyproject.toml-based projects.

I’m still on 2022.9.14

@miigotu @BKSteve Yelp !?

**Comment by miigotu** [comment] 2022-10-09 23:06
`CRYPTOGRAPHY_DONT_BUILD_RUST=1 pip install -U sickchill`

**Comment by miigotu** [comment] 2022-10-09 23:06
@twinden if you were installed with pip before, it doesn't need to build those again.
