### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_6 :: [6bfdb22] Unable to create the folder M:\Spartacus, can't add the show

### ISSUE THREAD

**Issue by TATUMTOT** [SickChill/SickChill#5546] opened 2019-06-24 08:47 UTC
### INFO
Python Version: **2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_6 :: [6bfdb22] Unable to create the folder M:\Spartacus, can't add the show
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by TATUMTOT** [comment] 2019-06-24 08:47
### INFO
Python Version: **2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [6bfdb22] Unable to create the folder M:\Spartacus, can't add the show
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment] 2019-06-25 09:16
Duplicate of #5547

**Closed** 2019-06-25 09:16 UTC
