### ISSUE TITLE
[APP SUBMITTED]: [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E19 - \xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xe4\xb8\x87\xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xce\xa8\xe6\x9e\x9c\xe3\x81\xa6\xe3\x81\xae\xe9\x81\x8a\xe5\x9c\x92\xe5\x9c\xb0\xe3\x81\xb8\xe3\x82\x88\xe3\x81\x86\xe3\x81\x93\xe3\x81\x9d\xef\xbc\x81\xef\xbc\x8f\xce\xa8\xe8\xa6\x8b(\xe3\x82\xb5\xe3\x82\xa4\xe3\x83\x81\xe3\x82\xa7\xe3\x83\xb3)\xef\xbc\x81\xe7\xa5\x96\xe7\x88\xb6\xe6\xaf\x8d\xe3\x81\xa8\xe3\x81\xae\xe5\x88\xa5\xe3\x82\x8c\xef\xbc\x8f\xe7\xa5\x9d\xe3\x82\xb2\xe3\x83\xbc\xe3\x83\xa0\xe5\

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4875] opened 2018-08-14 12:48 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/d7114f6f2ccaaa573fe27e16641fbaa4
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E19 - \xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xe4\xb8\x87\xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xce\xa8\xe6\x9e\x9c\xe3\x81\xa6\xe3\x81\xae\xe9\x81\x8a\xe5\x9c\x92\xe5\x9c\xb0\xe3\x81\xb8\xe3\x82\x88\xe3\x81\x86\xe3\x81\x93\xe3\x81\x9d\xef\xbc\x81\xef\xbc\x8f\xce\xa8\xe8\xa6\x8b(\xe3\x82\xb5\xe3\x82\xa4\xe3\x83\x81\xe3\x82\xa7\xe3\x83\xb3)\xef\xbc\x81\xe7\xa5\x96\xe7\x88\xb6\xe6\xaf\x8d\xe3\x81\xa8\xe3\x81\xae\xe5\x88\xa5\xe3\x82\x8c\xef\xbc\x8f\xe7\xa5\x9d\xe3\x82\xb2\xe3\x83\xbc\xe3\x83\xa0\xe5\x8c\x96\xef\xbc\x81\xe6\x96\x89\xe8\x97\xa4\xe9\x82\xa6\xe5\xa4\xab\xe3\x81\xae\xce\xa7\xe8\xab\x87 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 12:48
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/699a668a307c7ab2c459c39b8878f693
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 19 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E19 - 万Ψ！ツンデレおじいちゃん／万万Ψ！ツンデレおじいちゃん／Ψ果ての遊園地へようこそ！／Ψ見(サイチェン)！祖父母との別れ／祝ゲーム化！斉藤邦夫のΧ談 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 16:50
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/de54178d23aca7430b6c485272b2a33b
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E19 - \xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xe4\xb8\x87\xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xce\xa8\xe6\x9e\x9c\xe3\x81\xa6\xe3\x81\xae\xe9\x81\x8a\xe5\x9c\x92\xe5\x9c\xb0\xe3\x81\xb8\xe3\x82\x88\xe3\x81\x86\xe3\x81\x93\xe3\x81\x9d\xef\xbc\x81\xef\xbc\x8f\xce\xa8\xe8\xa6\x8b(\xe3\x82\xb5\xe3\x82\xa4\xe3\x83\x81\xe3\x82\xa7\xe3\x83\xb3)\xef\xbc\x81\xe7\xa5\x96\xe7\x88\xb6\xe6\xaf\x8d\xe3\x81\xa8\xe3\x81\xae\xe5\x88\xa5\xe3\x82\x8c\xef\xbc\x8f\xe7\xa5\x9d\xe3\x82\xb2\xe3\x83\xbc\xe3\x83\xa0\xe5\x8c\x96\xef\xbc\x81\xe6\x96\x89\xe8\x97\xa4\xe9\x82\xa6\xe5\xa4\xab\xe3\x81\xae\xce\xa7\xe8\xab\x87 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-14 16:50
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/b0e8c1852bac2e30fee4a61933a6de50
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 19 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E19 - 万Ψ！ツンデレおじいちゃん／万万Ψ！ツンデレおじいちゃん／Ψ果ての遊園地へようこそ！／Ψ見(サイチェン)！祖父母との別れ／祝ゲーム化！斉藤邦夫のΧ談 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:14
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/2e8b0b52083dbeddd90e2df34f15af2e
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 36] File name too long: '/volume1/Media/shared/Animes/TV Shows/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3/Season 01/\xe6\x96\x89\xe6\x9c\xa8\xe6\xa5\xa0\xe9\x9b\x84\xe3\x81\xae\xce\xa8\xe9\x9b\xa3 - S01E19 - \xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xe4\xb8\x87\xe4\xb8\x87\xce\xa8\xef\xbc\x81\xe3\x83\x84\xe3\x83\xb3\xe3\x83\x87\xe3\x83\xac\xe3\x81\x8a\xe3\x81\x98\xe3\x81\x84\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xef\xbc\x8f\xce\xa8\xe6\x9e\x9c\xe3\x81\xa6\xe3\x81\xae\xe9\x81\x8a\xe5\x9c\x92\xe5\x9c\xb0\xe3\x81\xb8\xe3\x82\x88\xe3\x81\x86\xe3\x81\x93\xe3\x81\x9d\xef\xbc\x81\xef\xbc\x8f\xce\xa8\xe8\xa6\x8b(\xe3\x82\xb5\xe3\x82\xa4\xe3\x83\x81\xe3\x82\xa7\xe3\x83\xb3)\xef\xbc\x81\xe7\xa5\x96\xe7\x88\xb6\xe6\xaf\x8d\xe3\x81\xa8\xe3\x81\xae\xe5\x88\xa5\xe3\x82\x8c\xef\xbc\x8f\xe7\xa5\x9d\xe3\x82\xb2\xe3\x83\xbc\xe3\x83\xa0\xe5\x8c\x96\xef\xbc\x81\xe6\x96\x89\xe8\x97\xa4\xe9\x82\xa6\xe5\xa4\xab\xe3\x81\xae\xce\xa7\xe8\xab\x87 - 1080p_HDTV.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:14
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/6a961d1ebc50a677f6b3e5e49bf3297d
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to link file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 19 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E19 - 万Ψ！ツンデレおじいちゃん／万万Ψ！ツンデレおじいちゃん／Ψ果ての遊園地へようこそ！／Ψ見(サイチェン)！祖父母との別れ／祝ゲーム化！斉藤邦夫のΧ談 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment] 2018-08-15 04:37
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to copy file /volume1/Media/torrents/downloads/sickrage/[HorribleSubs] Saiki Kusuo no Psi-nan - 19 [1080p].mkv to /volume1/Media/shared/Animes/TV Shows/斉木楠雄のΨ難/Season 01/斉木楠雄のΨ難 - S01E19 - 万Ψ！ツンデレおじいちゃん／万万Ψ！ツンデレおじいちゃん／Ψ果ての遊園地へようこそ！／Ψ見(サイチェン)！祖父母との別れ／祝ゲーム化！斉藤邦夫のΧ談 - 1080p_HDTV.mkv: error 36 : File name too long
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-11-30 17:21
Duplicate of #4868

**Closed by WebSpider** 2018-11-30 17:21 UTC
