### ISSUE TITLE
[APP SUBMITTED]: "There is no item named u'en.xml' in the archive"

### ISSUE THREAD

**Issue by psa99** [SickChill/SickChill#5693] opened 2019-11-17 02:44 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/685ebb527cf7c11bdf9914e31c03b306
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mmhere** [comment] 2019-11-17 03:40
duplicate of known issue gated bye thetvdb.com getting their act together
[https://github.com/SickChill/SickChill/issues/5686](https://github.com/SickChill/SickChill/issues/5686)

**Comment by psa99** [comment] 2019-11-17 04:06
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/899fa6ffdd767ef305ed25c8f59a592e
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LeeThompson** [comment] 2019-11-17 05:22
See #5686 for more information.

**Comment by Hisha** [comment] 2019-11-17 17:15
### INFO
Python Version: **2.7.9 (default, Sep 16 2019, 18:29:54) [GCC 4.9.2]**
Operating System: **Linux-4.14.98-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/c39f23db0527fc726c1c8e3c9b00dea3
### ERROR
```
SHOWQUEUE-REFRESH :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment] 2019-11-18 11:09
Duplicate of #5686

**Closed by WebSpider** 2019-11-18 11:09 UTC

**Comment by fatgeek** [comment] 2019-11-18 16:48
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/45687a50bb679f1bad9f09bfb6273577
### ERROR
```
SHOWQUEUE-REFRESH :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dporem** [comment] 2019-11-19 10:32
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/5068baab964bba90699c82619fed1295
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by potestus** [comment] 2019-11-19 12:06
### INFO
Python Version: **2.7.15 (default, Mar 21 2019, 20:32:32) [GCC 7.4.0]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/36fdeda916c5d05ab4e7ef415b786b51
### ERROR
```
POSTPROCESSOR-MANUAL :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/c12ceca3a5e985631dc584712f60aab5
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/True Detective on theTVDB using ID 270633, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/791851b313e73d7f7fbcc8dc79effdb6
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/Live Free or Die on theTVDB using ID 286522, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/ee8288aa0f29e1dc734772d1555a7ef4
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/Making a Murderer on theTVDB using ID 303210, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/02ed6544b1003966c8c4fa759a1f5ccb
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/Westworld on theTVDB using ID 296762, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/a1cc8b31e2dddaf11b1f07389ca3e59d
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/Mr. Robot on theTVDB using ID 289590, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/0eb851a38d978530d6b4ea1d28036116
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/SIX on theTVDB using ID 311809, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aklein84** [comment] 2019-11-20 03:42
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/223f1d61ef54e6c457314073d393d4b4
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/adam/Vikings on theTVDB using ID 260449, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by muscledsnow3475** [comment] 2019-11-20 08:09
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by imdpenguin** [comment] 2019-11-20 11:01
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-MANUAL :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by vanticar** [comment] 2019-11-20 20:31
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/1ffa395d8f3bcaad355e4f37613d697d
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment] 2019-11-21 02:06
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/4b3983eae06f82e944c8fb0be3841210
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment] 2019-11-21 02:22
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/451b4aa2d4a73c0cdead9d8d23aa3d83
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by well0549** [comment] 2019-11-21 17:12
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/3107f014a95f8fefb974d5444030b29e
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to TVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by well0549** [comment] 2019-11-21 17:12
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/23cc6ba2e4f5e4a892857e8a3d442c21
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by CQuillinan** [comment] 2019-11-22 04:13
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.184.x86_64.1-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4b69468cc1ea330f598364718068352a54b0eb92
Link to Log: https://gist.github.com/77c2fa37fce68ab69e67a9682d1e728d
### ERROR
```
POSTPROCESSOR-AUTO :: [4b69468] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by furafollas** [comment] 2019-11-22 07:15
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/49d3878f84a99080132afd7728855c78
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by well0549** [comment] 2019-11-22 18:39
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/ec56a814222892bb4133d0353965cc71
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to TVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by well0549** [comment] 2019-11-22 18:40
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/2521cf10ae982fc5fbb35a1abd08fe35
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dracupg** [comment] 2019-11-23 05:50
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-71-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kbelles** [comment] 2019-11-24 01:06
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.116.x86_64.1-x86_64-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/a708ace806ee3c0499ef3aee0aae590e
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kbelles** [comment] 2019-11-24 08:43
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.116.x86_64.1-x86_64-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kbelles** [comment] 2019-11-25 09:43
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.116.x86_64.1-x86_64-with-debian-8.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - "There is no item named u'en.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
