### ISSUE TITLE
Adding Show Error - Error 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by whiteazn** [SickChill/SickChill#7581] opened 2021-10-25 00:29 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Version: v2021.07.23-1 
OS: Win10
Browser: Firefox
What you did: Add Show (both manually, and with folders created
What happened:
What you expected:
Logs:
```
2021-10-23 16:30:54 There was an error creating the show in J:\Videos\TV Shows\Fighter Pilot The Real Top Gun: Error 'NoneType' object has no attribute 'split'
2021-10-23 16:30:27 There was an error creating the show in J:\Videos\TV Shows\The Cruise: Error 'NoneType' object has no attribute 'split'
2021-10-23 16:30:19 There was an error creating the show in L:\Videos\TV Shows\The Job Interview (2017): Error 'NoneType' object has no attribute 'split'
2021-10-23 16:30:19 There was an error creating the show in L:\Videos\TV Shows\The Super-rich and Us: Error 'NoneType' object has no attribute 'split'
```

I keep trying to add a show, but SC refuses to and keeps giving me this error.  Logs say it is an issue with thetvdb?

For example:

```
2021-09-26 14:27:21 ERROR :: SHOWQUEUE-ADD :: Error trying to add show: 'NoneType' object has no attribute 'split'
2021-09-26 14:27:21 ERROR :: SHOWQUEUE-ADD :: Unable to add show due to an error with theTVDB: 'NoneType' object has no attribute 'split'
2021-09-26 14:27:21 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: L:\Videos\TV Shows\The Job Interview (2017)
2021-09-26 14:27:10 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Filtering and sorting out excess results because exact match was checked
2021-09-26 14:27:09 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['the job interview', 'job interview'] on Indexer: theTVDB (exact: 0)
```

I am not sure what is causing it?  I only get the error with those above shows?

**Comment by BKSteve** [comment] 2021-10-30 07:08
If this was caused by the `exact` check box being checked **### Please confirm**
Then it is resolved with #7600

**Closed** 2021-11-06 04:11 UTC
Labels: Fixed
