### ISSUE TITLE
This show is queued to be refreshed

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/SickChill#6194] opened 2020-04-12 01:50 UTC
Branch/Commit:  current release
OS: ReadyNASOS 6.10.3
Browser: Chrome

All my shows seem to have the following notice at the top of the page, but it doesn't go away its stuck there:

```
This show is queued to be refreshed
```

Logs: https://gist.github.com/theskillwithin/e605650804ecef478351ddf17facdc44

**Comment by ronrosenfeld** [comment] 2020-04-12 10:10
I've had similar problems from time to time. If check **Server Status**, I will see many (most or all) of my shows stuck in the server queue, with no progress over several days. Restarting SickChill seems to clear it out, but no cause or fix has been put forth.

**Comment by sjmcinness** [comment] 2020-04-13 10:20
I just noticed mine was saying the same, seemingly stuck refreshing The Amazing Race on 2020-04-05, with every show queued behind it for that and each of the subsequent days. As @ronrosenfeld said, restarting SickChill fixed it and I was able to initiate a file re-scan for a handful of shows (the reason I discovered the issue), as I'd manually copied some files into place.
The issue wasn't holding up daily or backlog searches.

**Comment by ronrosenfeld** [comment] 2020-04-15 10:31
For me, as before, the shows remain "stuck in the queue" for the past 26 hours, and I now see in the log, an error message for each show:

```
2020-04-15 04:23:41 INFO     SHOWUPDATER :: Automatic update failed: xxxxxx is already being updated by Post-processor or manually started, can't update again until it's done.
2020-04-15 04:23:41 INFO     SHOWUPDATER :: Automatic update failed: xxxxxx is in process of being updated by Post-processor or manually started, can't update again until it's done.
2020-04-15 04:23:41 INFO     SHOWUPDATER :: Automatic update failed: xxxxxx is in process of being updated by Post-processor or manually started, can't update again until it's done.
```
Unfortunately, it seems this is not a reliably reproduceable problem, making a fix difficult.

**Comment by rd1** [comment] 2020-04-19 19:26
same here, had to reinstall sickchill due to another bug. and now after restoring my shows from yesterday's backup, they are all stuck at "This show is queued to be refreshed" and not moving.

On top of that SC is not seeing my network shares.

PC reboots and restarts of sickchill don't do any good.

**Comment by miigotu** [comment] 2020-04-20 10:58
This is due to thetvdb api being a pain in the ass, nothing i can do about it here. They will get it sorted out someday.

**Closed by miigotu** 2020-04-20 10:58 UTC
