### ISSUE TITLE
Sickchill package don't start after last GUI update

### ISSUE THREAD

**Issue by kretzu77** [SickChill/SickChill#8090] opened 2022-08-19 05:33 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: a369538827c08c1fb28c638bf877ff2b884176eb
OS: Synology DSM 7
Browser: Chrome

What you did: Updated sickchill from GUI

What happened: Sickchill package don't start anymore. I tried rebooting NAS, but no luck

![Untitled](https://user-images.githubusercontent.com/30404637/185549445-2544d587-b3ec-4988-ae3c-79c2fc41029b.jpg)

What you expected: to access sickchill GUI page from browser
Logs:
[sickchill.log](https://github.com/SickChill/SickChill/files/9379393/sickchill.log)

PASTE LOGS HERE
[sickchill.log](https://github.com/SickChill/SickChill/files/9379399/sickchill.log)

**Comment by BKSteve** [comment] 2022-08-19 07:32
See troubleshooting section
https://github.com/SickChill/SickChill/wiki/Synology

In regard logs, get this information from the DSM6 or DSM7 logs folder under `data` folder

**Comment by bneser** [comment] 2022-08-20 06:54
Confirmed. Same issue. Logs will be posted shortly.

**Comment by BKSteve** [comment] 2022-08-20 07:25
Look at #8068. 
Once you ssh in you'll be prepared

**Comment by bneser** [comment] 2022-08-20 07:43
Confirmed @BKSteve 
Thank you once again. You're such a valuable resource to the community. 

@kretzu77 check link above.

**Comment by BKSteve** [comment] 2022-08-20 07:54
What did you do? `ssl_verify` or `config.ini` ? https://github.com/SickChill/SickChill/issues/8068#issuecomment-1216774206

Now it's running and if you did `ssl_verify` if you do https://github.com/SickChill/SickChill/issues/8068#issuecomment-1220672441 and restart does it start?
I've never had this issue on any of my DSM or Debian test machines, so curious. Some have this problem and others don't

**Comment by BKSteve** [comment] 2022-08-20 07:55
closing as pretty sure it's all duplicate of #8068

**Closed by BKSteve** 2022-08-20 07:55 UTC
Labels: Duplicate, Fixed

**Comment by bneser** [comment] 2022-08-20 08:01
I changed the ssl_verify variable from 0 to 1 in the config.ini. 
Just restarting the NAS now to verify all in good.

**Comment by bneser** [comment] 2022-08-20 08:14
/volume1/@appdata/sickchill/data folder contents seems to lose it's write ability after restart, restarting once again to test.

**Comment by bneser** [comment] 2022-08-20 08:38
Error being trapped. 

2022-08-20 10:36:30 Failed parsing provider. Traceback: 'Traceback (most recent call last):\n File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/limetorrents.py", line 55, in search\n data = BeautifulSoup(data, language="xml")\n File "/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/bs4/__init__.py", line 254, in __init__\n builder = builder_class(**kwargs)\n File "/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/bs4/builder/_lxml.py", line 128, in __init__\n super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'

But the webpage is working.

**Comment by BKSteve** [comment] 2022-08-20 09:25
lime torrents see #8080

**Comment by bneser** [comment] 2022-08-20 10:04
changed the ssl_verify back to 0 and no issues. However sickchill does not restart when requested or restarting the NAS...

Endless loop... ?

Checking that ssl_verify setting again.

**Comment by kretzu77** [comment] 2022-08-23 16:31
> 

Solved. Thank you very much.
