### ISSUE TITLE
Sickrage not turning on. SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by unknownforce** [SickChill/SickChill#7114] opened 2021-05-04 05:11 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Up to date.
OS: Mac OSX 10.15.7
Browser: Chrome
What you did: It all started when I got a power outage and thats when it stopped working. Whenever I try to start it, it gives me that error. It was working perfectly fine before the power outage and now I don't know what to do. I've forced updated to the latest version. I looked into getting python3 which I already had installed. I installed the packages within XCode, it had updates or something to install. 
What happened: I keep getting this error. Sickrage isn't even turning on. 
What you expected: Start SickChill
Logs:
```
Traceback (most recent call last):
  File "/Applications/SickRage/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/Applications/SickRage/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/Applications/SickRage/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/Applications/SickRage/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/Applications/SickRage/sickchill/logger.py", line 72
    msg = re.sub(fr"\b({item})\b", "*" * 8, msg)
                                ^
SyntaxError: invalid syntax
```
Any help is great.

**Comment by sokushi-git** [comment] 2021-06-16 20:04
I have a similar error after the latest auto update.

```Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/opt/sickchill/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/opt/sickchill/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/opt/sickchill/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/opt/sickchill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/opt/sickchill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/opt/sickchill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined```

**Comment by sokushi-git** [comment] 2021-06-16 20:44
I tried reinstalling it via Git several times to no avail. But tried it with pip and it works.
Is there a version difference?

**Comment by kyuuk** [comment] 2021-06-16 21:22
Duplicate of #7177, you can find a workaround there to make it work while waiting for a fixed release

**Comment by unknownforce** [comment] 2021-06-16 21:38
> > I tried reinstalling it via Git several times to no avail. But tried it with pip and it works.
> > Is there a version difference?
> 
> it's not the same issue, but for your problem you can find a workaround in #7177 to make it work while waiting for a fixed release

I've tried that but it's still the same error keeps popping up. I even tried a fresh install and it's not working. I'm on a mac so I rather not have to upgrade to python 3 if I don't need to. It was working before until something happened. It was perfectly fine.

**Comment by kyuuk** [comment] 2021-06-16 21:47
i'm not 100% sure about what i'm gonna say, but i think Python3 is mandatory for SickChill !

**Comment by unknownforce** [comment] 2021-06-16 22:18
Yeah so I apparently I did managed to install Python3 but I'm now getting a different error. 

Traceback (most recent call last):
  File "/Applications/SickRage/SickChill.py", line 14, in <module>
    import sickchill.start
ImportError: No module named sickchill.start

**Comment by miigotu** [comment] 2021-06-18 03:39
Python 3.6+

**Closed by miigotu** 2021-06-18 03:39 UTC

**Comment by unknownforce** [comment] 2021-06-18 05:15
I'm still getting this error when i'm on Python 3.8

**Comment by miigotu** [comment] 2021-06-18 08:44
Reinstall maybe, you need to have up to date code.
