### ISSUE TITLE
Add providers YggTorrent & SpaceTorrent

### ISSUE THREAD

**Issue by PxReaz** [SickChill/SickChill#3915] opened 2017-07-09 21:24 UTC
Branch/Commit: master/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
OS: Linux-3.16.0-4-amd64-x86_64-with-debian-8.8

Hello!

this is not really an issue but can you add a provider in the next update?
or help me to add it manually i'm not sure how to do that

it's a new provider that is here to replace t411 who's been closed recently.

http://yggtorrent.com

Thanks!

**Comment by HLFH** [comment] 2017-07-11 09:02
spacetorrent.pw would also be interesting to add as a replacement of t411.

**Comment by PxReaz** [comment] 2017-07-11 09:11
Where did you get the invitation for this provider?

**Comment by HLFH** [comment] 2017-07-11 12:31
From https://www.wareziens.net/forum/, I got the email contact that is using ProtonMail. If you have a good profile, you were able to get the invitation code. Now it is more advised to create your own invitation topic, ask for a SPT.pw invitation, and if your profile match, you'll get it.

**Comment by PxReaz** [comment] 2017-07-11 15:19
Ok thanks! Hope they will add the providers in the next update!

**Comment by sharkykh** [comment] 2017-07-12 17:45
1. It seems yggtorrent is now under maintenance. I'll check again later.
2. I'm not going to work on spacetorrent.pw because it's a private tracker.

**Comment by PxReaz** [comment] 2017-07-12 18:10
Okay thanks !

**Comment by Amonbofils** [comment] 2017-07-13 08:07
ygg is back if you want to try :D

**Comment by HLFH** [comment] 2017-07-13 12:15
@sharkykh I can invite you on spacetorrent.pw if you want to work on it with some other SickRage users.

**Comment by antipiot** [comment] 2017-07-15 12:09
@HLFH Hey mate, if you don't bother sharing, i'm interested aswell :-)i was a daily user ot T411 with sickrage

**Comment by dmsimard** [comment] 2017-07-18 02:26
Relevant ? 
https://github.com/Jackett/Jackett/commit/35103206cfdb382d247ce089209b12abec4c5ada#diff-2eee82756efe0f23652a6a71efa6e983
https://github.com/Jackett/Jackett/commit/14f86107e14e3ec3823479d160cf91ad62365076#diff-2eee82756efe0f23652a6a71efa6e983

**Comment by jgrossrieder** [comment] 2017-08-06 12:13
I was wanting to implement this provider on SickRage, I did implement a big part of the provider, but I can't find any documentation on how to setup a development environment to test my implementation. Tried to request it through IRC couple of times, but no one was here to answer.

**Comment by adaur** [comment] 2017-08-06 13:31
I'll take a look at this asap

**Comment by adaur** [comment] 2017-08-06 15:25
Done https://github.com/SickRage/SickRage/pull/3956

**Comment by jgrossrieder** [comment] 2017-08-06 15:34
@adaur By the way it is required to login to download ;)
How do you test your code, I'm interessted in contributing too.

**Comment by adaur** [comment] 2017-08-06 15:36
Is it? Oh, they changed it recently my bad.

**Comment by jgrossrieder** [comment] 2017-08-06 15:39
@adaur yes, you can browse and everything, but you have to login get the .torrent. Because they track the ratio and include a passcode in the torrent url.

And for my other question? :)

**Comment by adaur** [comment] 2017-08-06 15:42
I use Python 2.7 and pyCharm as an IDE. Just run SickBeard.py in the CLI or directly from your IDE and you're good to go.

**Comment by jgrossrieder** [comment] 2017-08-06 16:11
@adaur Thanks you very much, I was thinking it was much more complicated! 👍

**Comment by AlexMihe** [comment] 2017-08-08 18:09
Hello,

With YggTorrent and SpaceTorrent, it would also be nice to add these providers :

- Arche Torrent
- Elite-Tracker
- Ethor.net (Thor's Land)
- Mania-Torrent (zetorrents.cc)
- Mononoké-BT
- NextTorrent	
- ShareSpaceDB	 
- Torrent9
- T411.si

Thanks !

**Comment by adaur** [comment] 2017-08-09 22:40
@AlexMihe some of the providers you are referring to are already supported

Space is too young and lacks a proper search engine. Elite would be interested to add though.

t411.si is a blatant scam

**Comment by yao89** [comment] 2017-08-15 12:04
Hello, i'm now on 'yggtorrent' branch, and setup yggtorrent as indexer is good, but i got issues every time it try to search episodes or season :
Error : https://cl.ly/m1XR
The torrent available : https://cl.ly/m1A6

Am I the only one to got these ?

**Comment by adaur** [comment] 2017-08-15 15:22
Please enable debug mode

**Comment by yao89** [comment] 2017-08-15 15:26
This bug was caused by the seeder min at 1. Set it to 0 make it found the torrent.
But know I got thoses :
https://cl.ly/m1HF

**Comment by yao89** [comment] 2017-08-16 12:06
Hi, just try with Deluge installed, and same thing.

**Comment by yao89** [comment] 2017-08-17 19:58
Hello all, to understand where is the problem, I try to switch to "develop" branch, and, IT'S WORK !
So there is a bug in "master" branch, how's not in develop one.

Have you any idea when yggtorrent will be integrated in this develop branch ?

Thanks a lot.

**Comment by jgrossrieder** [comment] 2017-08-19 10:51
@adaur Did you had the chance to look over the issue?

**Comment by yao89** [comment] 2017-08-19 15:11
Unfortunately, this works only with Rargb, not with yggtorrent..

**Comment by jgrossrieder** [comment] 2017-09-03 10:14
@adaur Did you stop working on this ? Should somebody else work on it?

**Comment by adaur** [comment] 2017-09-04 19:17
If you have a fix available, please PR the yggtorrent branch

**Comment by PxReaz** [comment] 2017-10-31 12:22
Hi everyone, is there any update on this?

Thanks!

**Comment by adaur** [comment] 2017-10-31 18:06
I'll work on it here https://github.com/pymedusa/Medusa/issues/3197

**Comment by PxReaz** [comment] 2017-11-02 09:44
Is yggtorrent also in the other issue ?

Le 31 oct. 2017 à 18:06, adaur <notifications@github.com<mailto:notifications@github.com>> a écrit :


Reopened #3915<https://github.com/SickRage/SickRage/issues/3915>.

**Comment by adaur** [comment] 2017-11-02 15:52
Ygg has already been merged in master there

**Comment by PxReaz** [comment] 2017-11-03 15:39
Really? I can’t see it!


Le 2 nov. 2017 à 15:53, adaur <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ygg has already been merged in master there

**Comment by antipiot** [comment] 2017-11-03 20:43
Same here, can't see it: no updates found aswell: Branch: master | Now: 11/03/17 09:42 PM

**Comment by Sylanorr** [comment] 2017-11-05 12:51
Same, last release installed but no YggTorrent found.

**Comment by yao89** [comment] 2017-11-05 14:14
Hi folks,

Install Medusa, more beautiful, speedup, and integrate directly Yggtorrent
;)



-- 

*Adrien Labigne*

Numéro : 0496 21 45 42 <//0496 21 45 42>

Site internet : yao-nas.myds.me

Le 5 novembre 2017 à 13:51:28, Sylanorr (notifications@github.com) a écrit:

Same, last release installed but no YggTorrent found.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SickRage/SickRage/issues/3915#issuecomment-341970766>,
or mute the thread

**Comment by adaur** [comment] 2017-11-05 17:45
By 'there' I meant Medusa

**Comment by jgrossrieder** [comment] 2017-11-05 23:18
@yao89 is there some tutorials on how uninstall SickRage, install medusa and use the same DB?

**Comment by adaur** [comment] 2017-11-06 00:24
https://mondedie.fr/d/6430-discussion-medusa-telechargement-automatique-depisodes-de-serie/1123
https://mondedie.fr/d/6429-Tuto-SickRage-telechargement-automatique-d-episodes-de-series-TV

**Comment by PxReaz** [comment] 2017-11-09 10:54
@jgrossrieder hi, what u can do is install medusa normally, set it up and then copy sickbeard.db of sickrage into main.db of medusa (keep the old main.db file in case of failure). That's what I did and it worked!

**Comment by AlexMihe** [comment] 2018-03-09 10:27
Hi everyone,
Could you tell me if the team is working on adding "Elite-Tracker" on Sickrage?

Thank you!!!

**Comment by AlexMihe** [comment] 2018-03-09 10:55
I saw that someone has been working on a request for Elite-Tracker but the issues hasn't been solved : https://github.com/SickRage/SickRage/pull/4013

Could someone take a look into it?

Thanks again!

**Closed** 2020-03-08 03:33 UTC
Labels: BACK-BURNER, Feature Request
