### ISSUE TITLE
Echelon destroyed my install (FreeNAS) - any help?

### ISSUE THREAD

**Issue by jaxjexjox** [SickChill/SickChill#5026] opened 2018-10-10 04:48 UTC
### Before submitting your issue:

Sickrage webUI is completely broken.
My jail is running, networking is working, I can ping in / out of my jail.
I need to 'repair' my install of sickrage and get rid of this idiots code.
How do I go about doing this, 
I do not have git installed in my FreeNAS jail, I don't know why? The plugin never needed it.  I suppose I can pull it down in the meantime.

**Comment by 2fst4u** [comment] 2018-10-10 08:51
I'm in the exact same boat. You're not alone. The plugin obviously doesn't use got so we're stuck on how to fix this.

Someone please help us on this, you're going on get a lot of people with this issue soon.

**Comment by WebSpider** [comment] 2018-10-10 08:58
The solution in #5022 should get you going again. We're terribly sorry this happened to you, please be patient as we find a solution.

**Comment by 2fst4u** [comment] 2018-10-10 09:06
It doesn't because we don't have git. The FreeNAS plugins don't use it.

**Comment by WebSpider** [comment] 2018-10-10 09:08
Then we would need the maintainer of the FreeNAS plugin, if anyone knows who that is, a mention would be nice 
(im returning to the project after at least 1.5 years of being busy with private and work matters ;-) )

**Comment by jaxjexjox** [comment] 2018-10-10 10:36
"[EFAULT] An error occured! Please read above"

So the plugin is probably still pointing to the bad git repository, so we can't install a fresh copy without it being terrible unfortunately.   So it'd be best if we simply repair the damaged one.

Do you need more information? I can post logs, or are just screwed without git to pull down fixed files?
Can we swear here? Cause fuck this echelon loser, fuck him and fuck his build, I'll NEVER switch to his shit copy and I'll make sure no one I know does.

Loser.

**Comment by OmgImAlexis** [comment] 2018-10-10 10:52
I guess you could probably use [the zip](https://github.com/SickChill/SickChill/archive/master.zip) to fix this up?

**Comment by OmgImAlexis** [comment] 2018-10-10 10:54
Can we please try and follow Github's community guidelines and avoid swearing, etc. we're above that. There's no reason to stoop back down to that level.

**Comment by jaxjexjox** [comment] 2018-10-10 11:05
No problem.   I think my opinion on the guy is pretty clear at this point

I'll try the zip, thank you.

**Comment by jaxjexjox** [comment] 2018-10-10 11:05
(You wouldn't know the precise path to extract that, would you?)

**Comment by phreaq** [comment] 2018-10-10 13:13
> Try this:
> Re-install (from the sickchill.zip)
> Don't update on first run
> Stop it
> Edit config.ini
> Replace "git_remote_url = https://github.com/SickRage/SickRage.git"
> with "git_remote_url = https://github.com/SickChill/SickChill.git "
> Restart
> Update

I followed these steps, and it still fails.

I am noticing a sickbeard.py and a sickrage.py after the update occurs, but the app won't restart. Manually starting either py just ends in a dos box flasking (I'm on Windows)

**Comment by WebSpider** [comment] 2018-10-10 14:51
@phreaq we would need some logfiles to see what's going on in your install.

**Comment by phreaq** [comment] 2018-10-10 15:16
Here’s some log info (and some more background.

First, I’ve downloaded the sickchill.zip, and extracted it to a local drive. 
I launch sickbeard.py, and the web page opens. 
I then shut down sickchill, and edit the config.ini file to “git_remote_url = https://github.com/SickChill/SickChill.git”
Relaunch sickbeard.py, web page opens, update… sickchill doesn’t reopen

> 2018-10-10 10:12:14 INFO     CHECKVERSION :: Checking for updates using SOURCE
2018-10-10 10:12:50 INFO     ThreadPoolExecutor-0_3 :: Config backup in progress...
2018-10-10 10:12:50 INFO     ThreadPoolExecutor-0_3 :: Config backup successful, updating...
2018-10-10 10:12:51 INFO     ThreadPoolExecutor-0_3 :: Creating update folder C:\Apps\SickChill\sr-update before extracting
2018-10-10 10:12:51 INFO     ThreadPoolExecutor-0_3 :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2018-10-10 10:12:57 INFO     ThreadPoolExecutor-0_3 :: Extracting file C:\Apps\SickChill\sr-update\sr-update.tar
2018-10-10 10:13:04 INFO     ThreadPoolExecutor-0_3 :: Deleting file C:\Apps\SickChill\sr-update\sr-update.tar
2018-10-10 10:13:04 INFO     ThreadPoolExecutor-0_3 :: Moving files from C:\Apps\SickChill\sr-update\SiCKRAGE-SiCKRAGE-ea0e19e to C:\Apps\SickChill

> 

The logs are still pointing to the other build, but the config.ini still shows sickchill. Not sure where that's coming from...

**Comment by YipYup** [comment] 2018-10-10 22:40
Class action lawsuit against echel0n?

**Comment by Pbroc** [comment] 2018-10-10 22:59
I think it would be a good idea for the owner of this fork to make a statement about what happen really, because personally I had auto update on, and now I don't know if my server is compromise or not.

From what I understand, the guy who took the original repo he's now able to send any files to anybody who still didn't notice the message on the web ui?

Please tell me I don't have to wipe my entire system because of this nonsense?

**Comment by 2fst4u** [comment] 2018-10-11 04:20
Any updates to this? My install is completely broken from this.

**Comment by OmgImAlexis** [comment] 2018-10-11 04:57
@Pbroc the reason he can still send updates to users is because Github allowed him to take over `Sickrage/Sickrage`. 😞

**Comment by mrktt** [comment] 2018-10-11 11:01
I've done something like this.

`jls`

to get the jail ID, 2 in my case

`jexec 2 /bin/tcsh`

to open a shell inside the jail
the service should be already stopped. otherwise

`service sickrage stop`

then

`rm -r /usr/pbi/sickrage-amd64/share/sickrage/SickRage`
`fetch --no-verify-peer "https://github.com/SickChill/SickChill/archive/master.zip"`
`unzip master.zip`
`mv SickChill-master /usr/pbi/sickrage-amd64/share/sickrage/SickRage`
`chown -R media:media /usr/pbi/sickrage-amd64/share/sickrage/SickRage`
`rm master.tar.gz`
`service sickrage start`

Probably a change of git_remote_url to https://github.com/SickChill/SickChill.git in /var/db/sickrage/config.ini (always inside the jail) is needed for future updates.
This has brought my installation back to life. 
However I don't know if it is the right way to fix this.

**Comment by 2fst4u** [comment] 2018-10-11 18:05
@mrktt thank God! You fixed it, you legend. My install is now up and running.

Now to turn off updates and do a configuration backup!

Thank you, dude.

**Comment by mrktt** [comment] 2018-10-13 15:36
@trenst I think that the freenas plugin doesn't really use git_remote_url. This morning my installation, despite having changed the link to sickchill, tried to update again from the old url. Probably what yours have done. So for the moment I'm going to simply download the master.zip from time to time until every reference to the old site is removed or che plugin itself is updated to use sickchill.

**Comment by tmikaeld** [comment] 2018-10-13 18:12
@mrktt Can confirm, upgrading from master.zip until resolved.

**Comment by rembomy** [comment] 2018-10-14 07:32
@mrktt Thank you!

**Comment by jaxjexjox** [comment] 2018-10-14 07:36
Guys, girls,

I'm on holiday unfortunately.

Can I confirm there's a single simple fix now?

**Comment by 2fst4u** [comment] 2018-10-14 07:36
Yes.

**Comment by jaxjexjox** [comment] 2018-10-18 07:38
Just wanted to thank whomever released that master.zip file.

I have an iocage, new 11.2 jail (migrated from warden) and this still fixed me up.

**Comment by kilroy05** [comment] 2018-11-21 16:23
I can confirm that @mrktt  solutions works for me as well (on Freenas)
There is one slight difference, which is the chmod command. My group and owner are different.
Thank you :)

**Comment by WebSpider** [comment] 2018-12-03 14:46
This seems to be solved for everyone, closing issue

**Closed by WebSpider** 2018-12-03 14:46 UTC
