### ISSUE TITLE
Can't add new shows or update existing, getting this error.

### ISSUE THREAD

**Issue by jrc27** [SickChill/SickChill#5703] opened 2019-11-19 09:27 UTC
2019-11-19 04:21:11 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: "There is no item named u'en.xml' in the archive"

**Comment by WebSpider** [comment] 2019-11-19 13:34
Duplicate of #5686

**Closed by WebSpider** 2019-11-19 13:34 UTC
