### ISSUE TITLE
Sending torrents to qBittorrent 4.2.0 RC fails

### ISSUE THREAD

**Issue by pjplaypus** [SickChill/SickChill#5747] opened 2019-12-05 08:44 UTC
It appears the webui API for qbittorrent has changed in version 4.2.0 RC. Haven't seen any documentation of this but can confirm the old command endpoint returns 404 while the v2 api works

Branch/Commit: master/2404f197697602a2bbfa8e6b39207229a94d37bb 
OS: Ubuntu
Browser: Firefox
What you did: Triggered a search for episode to be sent to qbittorrent 4.2.0 RC
What happened: torrent was found from rarbg but fails to be added to qbittorrent 4.2.0 RC
What you expected: torrent to be added to qbittorrent
Logs:
```
2019-12-05 21:37:26 WARNING  SEARCHQUEUE-MANUAL-311954 :: qbittorrent: Unable to send Torrent
2019-12-05 21:37:26 INFO     SEARCHQUEUE-MANUAL-311954 :: Request failed: 404 Client Error: Not Found for url: http://192.168.1.110:8082/command/download ()
2019-12-05 21:37:26 DEBUG    SEARCHQUEUE-MANUAL-311954 :: qbittorrent: Requested a POST connection to url http://192.168.1.110:8082/command/download and data: {u'urls': u'magnet:?xt=urn:btih:536ee09cbb8ce861f71137ddfef429a53bf9bc46&dn=Riverdale.US.S04E08.108...
2019-12-05 21:37:26 DEBUG    SEARCHQUEUE-MANUAL-311954 :: Calling qbittorrent Client
2019-12-05 21:37:26 INFO     SEARCHQUEUE-MANUAL-311954 :: Downloading Riverdale.US.S04E08.1080p.WEB.H264-TBS[rartv] from Rarbg
```

**Comment by kal728** [comment] 2019-12-05 12:49
Same problem

**Comment by Onno10** [comment] 2019-12-05 16:24
same on windows 10, chrome. Had to make the switch to another torrent client which is pretty sad

**Comment by bpapa9013** [comment] 2019-12-06 12:49
Same issue here, started happening right after the last qBt update, I just downgraded to qBt to 4.1.9.1 for the time being (downgrading appears to be as painless as upgrading). [fosshub/qbt-old](https://www.fosshub.com/qBittorrent-old.html)

**Comment by ngodber** [comment] 2019-12-07 07:50
+1

**Comment by procdaddy11** [comment] 2019-12-09 04:51
Same here, downgrading to 4.1.9 until this is fixed. https://www.fosshub.com/qBittorrent-old.html

**Comment by procdaddy11** [comment] 2019-12-09 04:53
API changes https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#api-v230

**Comment by Xx-Ness-xX** [comment] 2019-12-09 22:37
I have the exact same issue. Downgrading to 4.1.9.1 fixes the issue for now.

**Comment by tchabaud** [comment] 2019-12-17 22:32
@procdaddy11 : seems related to legacy api drop https://github.com/qbittorrent/qBittorrent/blob/master/Changelog#76

**Comment by Xx-Ness-xX** [comment] 2019-12-19 01:48
Any update on this?

Looks like ALL calls will need to be prefixed with /api/v2:

From https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#general-information

> All API methods are under /api/v2/APIName/methodName, where APIName is a certain subgroup of API methods whose functionality is related.

Also looks like the version call is now: `/api/v2/app/version`
There is also: `/api/v2/app/webapiVersion`

**Comment by tchabaud** [comment] 2019-12-19 06:52
@Xx-Ness-xX : if you wanna try I made a quick'n'dirty "works on my computer" quality level fix [available here](https://raw.githubusercontent.com/tchabaud/SickChill/qbittorrent_apiv2/sickbeard/clients/qbittorrent_client.py)

Note: pausing torrent not working at the moment, will try to fix this when I'll have some time.

**Comment by Xx-Ness-xX** [comment] 2019-12-20 03:48
> @Xx-Ness-xX : if you wanna try I made a quick'n'dirty "works on my computer" quality level fix [available here](https://raw.githubusercontent.com/tchabaud/SickChill/qbittorrent_apiv2/sickbeard/clients/qbittorrent_client.py).
> 
> Just copy this file in place of the old one, and restart Sickchill, if you're lucky, it should work 😆
> 
> Note: pausing torrent not working at the moment, will try to fix this when I'll have some time.

Thanks I will give it a try!

**Comment by Xx-Ness-xX** [comment] 2019-12-21 05:22
@tchabaud It works! Thank you. I did get an error saying cannot pause the torrent, but it gets the job done.

**Comment by tchabaud** [comment] 2019-12-21 22:54
@Xx-Ness-xX : pause issue fixed, [pull request submitted](https://github.com/SickChill/SickChill/pull/5785)

**Comment by boeggild** [comment] 2019-12-23 10:19
Didn't seems to have fixed the issue for me. Same error.

**Comment by tchabaud** [comment] 2019-12-30 21:30
@pjplaypus : pull request has been merged, if think you can close the issue if it's good for you.

**Comment by smilerz** [comment] 2020-01-02 21:26
This issue has been resolved in the latest release (at least for me).  
Note to anyone still having issues: you have to change the torrent client to qBittorrent APIv2

**Closed** 2020-01-07 23:42 UTC
Labels: Bug / Issue, Enhancement, Feature Request

**Comment by maybdom** [comment] 2020-01-08 22:51
I tried changing the client to qBitorrent APIv2 and still getting "Unable to Send Torrent"
My qBittorrent client is v4.2.1

**Comment by tchabaud** [comment] 2020-01-09 06:44
@maybdom : can you post the related sickchill debug log extract please ?

**Comment by ngodber** [comment] 2020-01-09 09:27
[sickchill.log](https://github.com/SickChill/SickChill/files/4039619/sickchill.log)
Confirming still having an issue. Debug log attached.

**Comment by ngodber** [comment] 2020-01-09 12:54
This is using qbit 4.2.1 @tchabaud

**Comment by ngodber** [comment] 2020-01-09 14:35
@tchabaud @maybdom @miigotu Digging around I realised that my linuxserver.io sickchill docker image was actually not pulling the latest commits to master. So the issue was there not here. Depending if @maybdom is using the same method as me, it might explain it all.

**Comment by ngodber** [comment] 2020-01-09 22:07
@tchabaud turns out it was something of a wild goose chase. Confirmed now that I am in fact using the latest version which includes your code so this bug is still very much alive. @miigotu Could you reopen please?

**Comment by maybdom** [comment] 2020-01-09 22:38
@tchabaud Can you provide me how do I get you the logs?
@ngodber I did try to update Sickchill but not sure if it updated. Currently using the following:


Branch: master
Commit: 17e379df7dadc7711db1c76695411267f245a961
Version: v2020.01.03-1
Database Version: 44.1

**Comment by ngodber** [comment] 2020-01-09 22:45
@maybdom that is the latest version. To enable debug logging got settings > advanced > enable debug logging (checkbox). Then reproduce the bug (most likely by manually triggering a search). Log files should be in your config folder. Make sure to disable debug once done.

**Comment by maybdom** [comment] 2020-01-09 22:51
[sickchill.log](https://github.com/SickChill/SickChill/files/4042924/sickchill.log)

@ngodber I had a huge log file so I got you the one for the manual search I did. Let me know if you need more.

**Comment by tchabaud** [comment] 2020-01-09 23:03
@maybdom @ngodber : can you also provide qbitorrent log file please ? I'll have some time this week-end, I'll try to have a look at this.

**Comment by maybdom** [comment] 2020-01-09 23:10
@tchabaud @ngodber I think I should just go live in a cave. When I tested the connection to my torrent provider it said connected & authenticated. When I was getting logs for qbit, I noticed that it said invalid credentials. I updated the credentials on qbit and Sickchill and it worked. Not sure why on Sickchill it was able to authenticate while the credentials (apparently) were wrong on qbit. :/

**Comment by tchabaud** [comment] 2020-01-09 23:14
Perhaps there is a bug with the authentication test and the new qbit api. I'll check this, I'll let you know. Thanks for the details.

**Comment by ngodber** [comment] 2020-01-10 00:19
Hi,

Realised for me it was a case of PEBCAK - I didn't realise it was necessary to select specific API version in torrent provider. I was going to suggest polling API version and handling appropriate calls programmatically but I'm a bit confused as to how to do that. Ping'd Qbit devs to get there input:

https://github.com/qbittorrent/qBittorrent/pull/7610#issuecomment-572816586

Cheers

**Comment by brestfloda** [comment] 2020-02-13 06:27
Any news? It still fails for me. And yes, my connection tests just fine.

**Comment by ngodber** [comment] 2020-02-13 06:52
You need to go to settings and selection select qbit api version (there are two entries for qbit in the provider drop down now. I missed it as well.)

**Comment by procdaddy11** [comment] 2020-02-13 12:53
You need to change your client to v2

**Comment by brestfloda** [comment] 2020-02-13 16:17
Completely missed that! Thank you, it works now :)
