### ISSUE TITLE
AttributeError: module 'requests.exceptions' has no attribute 'InvalidJSONError'

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#7866] opened 2022-02-17 09:01 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: d19b6f847ea789d9c1c9935e15429d1657675b2f
OS:windows 10
Browser:chrome
What you did:Nothing. Sickchill updated itself 
What happened:Nothing. Sickchill crashed
What you expected:That it wouldn't crash 🤔🤣
Logs:
```
Checking poetry
sickchill installed: True
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "C:\SickChill\sickchill\__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "C:\SickChill\sickchill\tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "C:\SickChill\sickchill\oldbeard\providers\__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "C:\SickChill\sickchill\oldbeard\helpers.py", line 1315, in <module>
    requests.exceptions.InvalidJSONError,
AttributeError: module 'requests.exceptions' has no attribute 'InvalidJSONError'
```

**Comment by Tiwas** [comment] 2022-02-17 09:01
Trying a "git pull" returns "Already up to date"

**Comment by BKSteve** [comment] 2022-02-17 09:22
Your on windows so you should have a pip install.
Should be `pip3 install -U sickchill`

**Comment by Tiwas** [comment] 2022-02-17 09:25
> You're on windows so you should have a pip install. Should be `pip3 install -U sickchill`

Should that even be necessary when updating?

**Comment by Tiwas** [comment] 2022-02-17 09:46
> You're on windows so you should have a pip install. Should be `pip3 install -U sickchill`

There's no pip3 in the .\Python3\tools folder. Using the Python3 in my path gives me the following error
`ERROR: Could not build wheels for cryptography, pynacl which use PEP 517 and cannot be installed directly`

Scrolling up a bit, there's at least one reference to a missing compiler (I think)
```
  Exception: ERROR: The 'make' utility is missing from PATH
  ----------------------------------------
  ERROR: Failed building wheel for pynacl
```

**Comment by Tiwas** [comment] 2022-02-17 09:57
Ok, so I upgraded pip after googling a bit. The `pip3 install -U sickchill` then worked fine. Still same error when starting sickchill. Tried running it using the python-version in my path, but still getting the same error.

**Comment by Ulrar** [comment] 2022-02-17 10:55
Same issue here, using `linuxserver/sickchill` which just updated

**Comment by BKSteve** [comment] 2022-02-17 13:05
Just pondering the cause. Is it the latest SC updates or something else. Such as recent updates to `importlib.metadata` as I'm guessing that's where it's occurring from where it comes in the code.

What version of `importlib.metadata` is installed? The latest 4.11.1 or 4.8.2?
I'm travelling so don't currently have any ability to test, so will have to leave to others.

Latest commit d19b6f847ea789d9c1c9935e15429d1657675b2f

**Comment by Tiwas** [comment] 2022-02-17 13:26
> Just pondering the cause. Is it the latest SC updates or something else. Such as recent updates to `importlib.metadata` as I'm guessing that's where it's occurring from where it comes in the code.
> 
> What version of `importlib.metadata` is installed? The latest 4.11.1 or 4.8.2? I'm travelling so don't currently have any ability to test, so will have to leave to others.
> 
> Latest commit [d19b6f8](https://github.com/SickChill/SickChill/commit/d19b6f847ea789d9c1c9935e15429d1657675b2f)

How can I check that? The output from pip3 install only lists importlib-resources-5.4.0

**Comment by Tiwas** [comment] 2022-02-17 13:27
![image](https://user-images.githubusercontent.com/17053402/154491145-8419ba43-49aa-4198-927d-0bac8cebd88f.png)

**Comment by Tiwas** [comment] 2022-02-17 13:44
> I don't think that's the issue. I just tried upgrading requests (from 2.25 to 2.27) in my container and sickchill is now starting fine, I think it's just an outdated dependency.
> 
> Hopefully that can be fixed up properly so that new container images can have the correct version shipped in, but in the meantime people can just run `pip3 install --upgrade requests` to get back up and running.

That didn't work for me
```
C:\SickChill>pip3 install --upgrade requests
Requirement already satisfied: requests in c:\python\python38-32\lib\site-packages (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python38-32\lib\site-packages (from requests) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in c:\python\python38-32\lib\site-packages (from requests) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python\python38-32\lib\site-packages (from requests) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\python38-32\lib\site-packages (from requests) (1.25.10)

C:\SickChill>python.exe SickChill.py
Checking poetry
sickchill installed: True
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "C:\SickChill\sickchill\__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "C:\SickChill\sickchill\tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "C:\SickChill\sickchill\oldbeard\providers\__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "C:\SickChill\sickchill\oldbeard\helpers.py", line 1346, in <module>
    urllib3.exceptions.InvalidChunkLength,
AttributeError: module 'urllib3.exceptions' has no attribute 'InvalidChunkLength'
```

**Comment by Ulrar** [comment] 2022-02-17 13:46
@Tiwas Ah I also installed importlib.metadata, forgot about that. It didn't solve my issue until I upgraded requests but maybe both are required, try `pip3 install importlib.metadata`

**Comment by Ulrar** [comment] 2022-02-17 13:47
Just noticed you have a different issue there, it's not the same exception anymore. I bet you you need to upgrade urllib3

**Comment by Tiwas** [comment] 2022-02-17 13:48
> Just noticed you have a different issue there, it's not the same exception anymore. I bet you you need to upgrade urllib3

That fixed it! Thanks :)

**Comment by Ulrar** [comment] 2022-02-17 13:51
That's great news, so this is just a dependency problem. I don't know how dependencies are handled but since the linuxserver image is being generated with the wrong version of requests, I imagine they're defined somewhere in the repo and someone forgot to bump the version in a file.
Hopefully someone who knows how this works on sickchill can comment on that

**Comment by mufapu** [comment] 2022-02-17 14:11
For me it was fixed by running both `pip3 install importlib.metadata` and `pip3 install --upgrade requests`.
Hope others have similar luck.

Thanks for the feedback!

**Comment by BKSteve** [comment] 2022-02-17 14:13
The poetry.lock file contains 

> name = "urllib3" version = "1.26.8"
> name = "importlib-metadata" version = "4.8.3"
> name = "requests" version = "2.27.1"

So wonder what's stopping this update process?

**Comment by BKSteve** [comment] 2022-02-17 14:37
> For me it was fixed by running both `pip3 install importlib.metadata` and `pip3 install --upgrade requests`. Hope others have similar luck.
What versions did they update from and to?

It also seems odd that installing something that should have been already installed is the issue when updating.
That being `importlib.metadata`

**Comment by mufapu** [comment] 2022-02-17 15:02
> > What versions did they update from and to?

Sorry, no longer have the output. requests updated to version 2.27.1, importlib-metadata to 4.11.1

**Comment by miigotu** [comment] 2022-02-17 19:08
fooook, every time I update master \o/

**Comment by miigotu** [comment] 2022-02-17 19:17
https://github.com/urllib3/urllib3/blame/main/src/urllib3/exceptions.py#L303
That exception was added 2 years ago....

**Closed** 2022-02-17 19:28 UTC

**Comment by miigotu** [comment] 2022-02-17 19:42
Should be fixed, git pull or pip install -U or however you manually update.

**Comment by Ulrar** [comment] 2022-02-17 22:34
Latest linuxserver image does seem to be working fine, thanks for the quick fix !

**Comment by Telecart** [comment] 2022-02-18 05:05
That fixed it where all other prior advice failed! Didn't think to check so quickly for a new update, thanks for the fix!

**Comment by drn** [comment] 2022-02-19 04:54
Thanks for the fix! 🔥
