### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [1d34bcb] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by jheredianet** [SickChill/SickChill#4570] opened 2018-04-07 09:14 UTC
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.16.0-999-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [1d34bcb] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 22:49
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:49 UTC
