### ISSUE TITLE
Sickchill and qbittorrent are having a tizzy

### ISSUE THREAD

**Issue by samjaninf** [SickChill/SickChill#5774] opened 2019-12-19 19:59 UTC
Branch/Commit: master
OS: Debian / Linux-4.19.0-6-amd64-x86_64-with / Docker
Browser: Chrome
What you did: N/A
What happened: Sickchill is no longer able to send shows to qBittorrent
What you expected: Sickchill to send shows to qBittorrent and have them accepted.
Logs:
```
2019-12-19 14:52:51 DEBUG    SEARCHQUEUE-BACKLOG-280619 :: qbittorrent: Requested a POST connection to url http://qbittorrent:8080/command/download and data: {u'urls': u'magnet:?xt=urn:btih:1872bca1746e783735b85e0b56a808afa041a90a&dn=The.Expanse.S04.1080p.A...
2019-12-19 14:52:51 INFO     SEARCHQUEUE-BACKLOG-280619 :: Request failed: 404 Client Error: Not Found for url: http://qbittorrent:8080/command/download (<type 'str'>)
2019-12-19 14:52:51 WARNING  SEARCHQUEUE-BACKLOG-280619 :: qbittorrent: Unable to send Torrent
20
```
I believe this was probably cause by qbittorrent updating their api maybe I could be wrong.

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#download-torrent-from-url

**Comment by miigotu** [comment] 2019-12-19 20:02
Fix your qbittorrent. It obviously isn't found

**Comment by n2burns** [comment] 2019-12-20 03:02
Duplicate of [issue 5747](https://github.com/SickChill/SickChill/issues/5747).

**Comment by samjaninf** [comment] 2019-12-20 03:25
You're absolutely right @n2burns. Didn't do my due research diligence.

**Closed** 2019-12-20 03:25 UTC
