### ISSUE TITLE
Add show by IMDB tt id?

### ISSUE THREAD

**Issue by Bigdesertdon** [SickChill/SickChill#5691] opened 2019-11-16 21:51 UTC
I'm not sure how to resolve this.  I'm not even sure if this is related to a bug, but there appears to be two shows right now that are named the same.  One is a 3-episode mini series and one is a new series with a first 8-episode season.

War of the Worlds (2019) - 8 Episodes Season 1
https://www.imdb.com/title/tt9686194/
This is successfully loaded in SickChill

War of the Worlds (2019) - 3 Episode Mini-Series
https://www.imdb.com/title/tt8001226/

Thoughts?

If this isn't the place for this -- please advise.

**Comment by LeeThompson** [comment] 2019-11-17 05:26
_Right now since thetvdb's API is experiencing a widespread outage this won't work_ but when it's back online you can try searching for "The War of the Worlds" for the BBC mini-series.   Searching for "War of the Worlds (2019)" should find the Canal+ series.

(Having said that being able to search from an imdbid or a tvdb id directly would be great.)

BBC Mini Series: https://www.thetvdb.com/series/the-war-of-the-worlds  (tvdbid: 348204)
Canal+ Series: https://www.thetvdb.com/series/war-of-the-worlds-2019 (tvdbid: 370139)

**Comment by WebSpider** [comment] 2019-11-18 11:09
Duplicate of #5686

**Closed by WebSpider** 2019-11-18 11:09 UTC
