### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E03 - The Demonic Revenge Of Gil Berg - 1080p_BluRay.mkv'

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4897] opened 2018-08-14 15:08 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [0e72764] Failed renaming /volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Dangaioh Hyper Combat Unit - S00E03 - The Demonic Revenge of Gil Berg - 1080p_Bluray.mkv to /volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E03 - The Demonic Revenge Of Gil Berg - 1080p_BluRay.mkv : [Errno 13] Permission denied: '/volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E03 - The Demonic Revenge Of Gil Berg - 1080p_BluRay.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-11-30 17:18
Duplicate of #4869

**Closed** 2018-11-30 17:18 UTC
