### ISSUE TITLE
getting HTTPResponse has no attribute strict

### ISSUE THREAD

**Issue by wokka1** [SickChill/sickchill#8437] opened 2023-05-11 17:07 UTC
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.1.2 pip install
OS: gentoo on whatbox.ca, python 3.10.10
Browser: chrome
What you did: updated to latest version, checked logs, enabled debugs and restarted
What happened: getting a lot of AA AttributeError: 'HTTPResponse' object has no attribute 'strict'
What you expected: no errors
Logs:
```
AA AttributeError: 'HTTPResponse' object has no attribute 'strict'
AA u"strict": response.strict,
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/serialize.py", line 54, in dumps
AA self.serializer.dumps(request, response, body),
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/controller.py", line 274, in _cache_set
AA self._cache_set(cache_url, request, response, body, expires_time)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/controller.py", line 353, in cache_response
AA self.__callback(result)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 76, in _close
AA self._close()
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 96, in read
AA return self._fp.read(amt) if amt is not None else self._fp.read()
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/urllib3/response.py", line 794, in _fp_read
AA data = self._fp_read(amt) if not fp_closed else b""
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/urllib3/response.py", line 809, in _raw_read
AA data = self._raw_read(amt)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/urllib3/response.py", line 874, in read
AA data = self.read(amt=amt, decode_content=decode_content)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/urllib3/response.py", line 935, in stream
AA yield from self.raw.stream(chunk_size, decode_content=True)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/requests/models.py", line 816, in generate
AA self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/requests/models.py", line 899, in content
AA r.content
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/requests/sessions.py", line 745, in send
AA resp = self.send(prep, **send_kwargs)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
AA response = session.request(
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 1242, in getURL
AA raise requests_exception
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 1397, in handle_requests_exception
2023-05-11 11:31:24 ERROR :: MAIN :: Request failed: 'HTTPResponse' object has no attribute 'strict' (AttributeError)
AA AttributeError: 'HTTPResponse' object has no attribute 'strict'
AA u"strict": response.strict,
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/serialize.py", line 54, in dumps
AA self.serializer.dumps(request, response, body),
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/controller.py", line 274, in _cache_set
AA self._cache_set(cache_url, request, response, body, expires_time)
AA File "/mnt/mpathg/wokka/sickchill/lib/python3.10/site-packages/cachecontrol/controller.py", line 353, in cache_response

```

**Comment by ptitjano** [comment] 2023-05-11 22:22
This comes from urllib3. The `strict` parameter has been removed in the 2.0.0 version: https://urllib3.readthedocs.io/en/stable/changelog.html#id3.

**Comment by corzocone** [comment] 2023-05-12 20:16
> This comes from urllib3. The `strict` parameter has been removed in the 2.0.0 version: https://urllib3.readthedocs.io/en/stable/changelog.html#id3.

Is there a fix on the user side, or do we wait for an update from admins?

**Comment by ptitjano** [comment] 2023-05-12 20:24
> > This comes from urllib3. The `strict` parameter has been removed in the 2.0.0 version: https://urllib3.readthedocs.io/en/stable/changelog.html#id3.
> 
> Is there a fix on the user side, or do we wait for an update from admins?

If you installed sickchill with pip, this command should work. This will downgrade some packages while the problem is being sorted out: 

```sh
pip install -U requests==2.28.2 urllib3==1.26.15
```

**Comment by corzocone** [comment] 2023-05-12 20:28
> > > This comes from urllib3. The `strict` parameter has been removed in the 2.0.0 version: https://urllib3.readthedocs.io/en/stable/changelog.html#id3.
> > 
> > 
> > Is there a fix on the user side, or do we wait for an update from admins?
> 
> If you installed sickchill with pip, this command should work. This will downgrade some packages while the problem is being sorted out:
> 
> ```shell
> pip install -U requests==2.28.2 urllib3==1.26.15
> ```

I am running in a docker container. I will just wait for a fix.

**Comment by Smokey23** [comment] 2023-05-13 03:16
This issue just started hitting me in my docker container.  If you are using Portainer to manage your docker containers, it is pretty easy to apply the fix above.

1. Log in to Portainer.
2. Go to the "Containers" option on the left.
3. Select your sickchill container from the Containers List.  (Click it's name to open it)
4. In the "Container Status" section, click the ">_ Console" link at the bottom of the section.
5. CLick the "Connect" button at the bottom of the section.
6. Once at the prompt, paste in the 'pip' command `pip install -U requests==2.28.2 urllib3==1.26.15`
7. Once it is done, press the "Disconnect" button above the console
8. Return to the SickChill container using the breadcrumbs at the top of the page "Containers > sickchill"  (or whatever you called your container)
9.  Under "Actions" at the top of the page, click "Restart" to restart the container.

Once it restarts, you should be using the older version and it should work correctly.  I just did this exact thing and it worked great.  BTW, if you are not using Portainer to manage your docker stuff, you really should.  It makes managing everything so much easier and it's free.

I hope this helps..

Smokey

**Comment by corzocone** [comment] 2023-05-15 18:47
Thanks, @Smokey23 I've followed your directions. Out of curiosity, will I want to undo this process in the future when it is no longer broken? Or can this be left permanently?

**Comment by ptitjano** [comment] 2023-05-15 20:29
> Thanks, @Smokey23 I've followed your directions. Out of curiosity, will I want to undo this process in the future when it is no longer broken? Or can this be left permanently?

You don't need to do anything. Once this is fixed and a new sickchill version is available, this will be automatically updated.

**Comment by corzocone** [comment] 2023-05-19 18:53
@Smokey23 @ptitjano 

Sickchill just updated to 823a441b9d72 via watchtower. I seem to be getting the same "strict" error. Should I apply the same fix again?

**Comment by ptitjano** [comment] 2023-05-20 16:47
> @Smokey23 @ptitjano
> 
> Sickchill just updated to 823a441b9d72 via watchtower. I seem to be getting the same "strict" error. Should I apply the same fix again?

yes

**Comment by krash1220** [comment] 2023-05-23 00:38
Could someone please help me with this? I am on Windows 11 and I was having problems with errors with SickChill and so I did a clean install with the windows installer but now I'm getting this same error. And I don't know how to fix it. I ran the above command pip install -U requests==2.28.2 urllib3==1.26.15 but apparently the windows installer doesn't install pip? And there are no instructions how to install SickChill with pip.  https://github.com/SickChill/SickChill/wiki/Pip I went to this place but it only tells you how to upgrade an already installed version and the command uses pip. Do I install pip for windows or install pip with python? I can not use SickChill at all at this point.
2023-05-22 16:14:48 Request failed: 'HTTPResponse' object has no attribute 'strict' (AttributeError)
2023-05-22 16:14:47 Exception generated in thread CHECKVERSION: 'HTTPResponse' object has no attribute 'strict'

**Comment by miigotu** [comment] 2023-05-28 00:09
Fixed in latest release.

**Closed by miigotu** 2023-05-28 00:09 UTC
