### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E01 - Cross Fight!! - 1080p_BluRay.mkv'

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4895] opened 2018-08-14 14:55 UTC
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [0e72764] Failed renaming /volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Dangaioh Hyper Combat Unit - S00E01 - Cross Fight!! - 1080p_Bluray.mkv to /volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E01 - Cross Fight!! - 1080p_BluRay.mkv : [Errno 13] Permission denied: '/volume1/Media/shared/Animes/TV Shows/Dangaioh/Season 00/Great Dangaioh - S00E01 - Cross Fight!! - 1080p_BluRay.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by BenjV** [comment] 2018-08-14 15:03
Why 28 times the same issue report?

You apparently have an Synology Nas and the do not gave permissions correct permissions.
Please read this wiki and act on it.
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by janusn** [comment] 2018-08-16 09:14
Hi BenjV,

Sorry I didn't know about submission for 28 times. Was it a bug?

I have fixed the permissions as shown. Thank you very much.

However, there are warnings about failures of creating hard links in
post-processing even I have given full access to sc-sickrage. I tried ssh
on the NAS. Hard links are created fine with my administration account.
However, sudo -u sc-sickrage failed even I have given sc-sickrage full
access to both source and target folders. What's give?

Could you enlighten me on how to fix it? Thanks in advance!

Cheers,
Janus

**Comment by BenjV** [comment] 2018-08-16 09:48
Don't mess with the user sc-sickrage on DSM.
As of DSM 6 the user used to run package is hidden en DSM does not allow you to do anything with it.
The permissions has to be given via the group permissions.
First of all did you read the whole wiki and did you check if your share is ACL enabled?
Secondly, the existing folders and files don't change their permissions after you updated to the DSM 6 enabled package.
For existing folders, subfolders and files you have to set the correct group permissions via FileStation (don't forget to tick the recursive item in the left below corner of the wizard screen).

By the way why are you using hardlinks, make little sense to me?

**Comment by janusn** [comment] 2018-08-16 10:11
Dear BenjV,

Thanks for the quit reply! I deeply appreciate it.

I have read the page from the link a few times. Does it mean I have to
change the permissions of group sc-download on related folders only?

The reason I use hard links for post processing was:
I download the torrents with transmissions. I would like to seed the
torrents awhile after mine has done. Using hard links was suggested by the
popup at the settings page. Do you mean I should use copy and utilizes the
quick clone feature of DSM instead?

Thank you a ton!

Cheers,
Janus

**Comment by BenjV** [comment] 2018-08-16 10:55
Yes just the folder you need to access by Sonarr, so in the case the folder where Transmission put the files.

I suggest you use copy to another location and let Transmission finish the seeding.
After finishing the seeding, you just remove the torrent and the files together.

If you do it this way, you can also use the functionality of the Sonarr postprocessor to create for example show and season folders instead of the mesh you get in the Transmission downloaded folder.

**Comment by janusn** [comment] 2018-08-16 14:17
Dear BenjV,

Thanks for your advice.

However, the sickrage reported permissions errors when I took out the
privileges of the sc-sickrage users from both source and target folders. It
seems user sc-sickrage is used for some operations.

As the ACL settings, I have just recent bought the NAS and I upgrade to DSM
6.2-23739 Update 2 and enabled ACL on the shared folders before cloning the
files and installation of sickrage spk. Hence ACL should have been used on
all the folders and files.

Using copy for post-processing still consume double space and delay the
processing. Is hard link really not advised? I have used hard link for
post-process on sickrage plugin on FreeNAS for ages. I didn't encounter any
problem caused by hard link over there yet.

Cheers,
Janus

**Comment by BenjV** [comment] 2018-08-16 14:41
Hardlink should not give problems but it is messy with all those files in the downloadfolder.

If you do a copy, then you can delete the video after they reached the seeding limits.
And sure the video's that you are still seeding need double the disk space, but what is the problem with that, diskspace is cheep and an empty disk is not cheeper then a full disk.

**Comment by WebSpider** [comment] 2018-11-30 17:19
Duplicate of #4869

**Closed by WebSpider** 2018-11-30 17:19 UTC
