### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_2 :: [2a781a0] Missing time zone for network: Fox España. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by bepece1** [SickChill/SickChill#5121] opened 2018-10-26 14:10 UTC
### INFO
Python Version: **2.7.14 (default, Feb 22 2018, 21:59:41) [GCC 6.3.0]**
Operating System: **Linux-4.14.70-v7+-armv7l-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@2a781a0356e952c3e25890286aade058083bd0c1
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [2a781a0] Missing time zone for network: Fox España. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mmhere** [comment] 2018-10-27 00:01
Duplicate of 5119, which wraps together all current known missing network:timezone pairs.

**Comment by WebSpider** [comment] 2018-10-27 01:15
Please see #5119

**Closed by WebSpider** 2018-10-27 01:15 UTC
