### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [f30a844] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by MotleyC** [SickChill/SickChill#4309] opened 2018-02-12 05:33 UTC
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [f30a844] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment] 2018-02-17 06:00
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-332525 :: [f30a844] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment] 2018-02-17 06:00
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f30a84430b444bbd39308bfb8ff85ca17a48abd1
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-299139 :: [f30a844] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment] 2018-12-02 22:50
Duplicate of #4230

**Closed by WebSpider** 2018-12-02 22:50 UTC
